#!/usr/bin/env pwsh
# =============================================================================
# SENTINEL APEX -- AI Cyber Brain Fix Commit Script
# Generated by: CYBERDUDEBIVASH Cowork Session (2026-05-13)
# =============================================================================
# Commits 3 files fixing 4 AI Cyber Brain / APEX AI bugs:
#
#   1. index.html
#      - BUG #1 (P0): Removed stray ──── box-drawing line 5274 inside <script>
#        → was causing SyntaxError, window._v149AvgRisk never defined
#        → ERROR: window._v149AvgRisk is not a function on REFRESH ANALYSIS
#      - BUG #3 (P1): Added data.items to _fetchLiveIntel() parser fallback
#        → api/apex_v2/priority.json & critical.json use 'items' key (not 'data')
#        → AI Brain panels now get live intel from apex_v2 endpoints
#      - BUG #4 (P2): Wired ai-bar-predicted and ai-bar-lastrun in runAIBrain()
#        → Status bar High-Risk 30d count + last-run timestamp now populated
#
#   2. scripts/v149_frontend_dedup_patch.py
#      - BUG #2 (P0): Fixed partial str.replace() on box-drawing end marker
#        → insert_after "── end v149 DEDUP GUARD ──" matched first 30 chars of
#          longer "──────────────────────────────────────────────────────────────────────"
#        → remaining ────── chars left as bare JS statement → next pipeline run
#          would re-introduce SyntaxError
#        → Fix: DEDUP_GUARD_JS end marker changed to plain ASCII [end-v149-dedup-guard]
#        → Legacy HTML backward-compat matching preserved in insertion logic
# =============================================================================

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RepoRoot

Write-Host "`n============================================================" -ForegroundColor Cyan
Write-Host " SENTINEL APEX -- AI Cyber Brain Fix Commit" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# ── Step 1: Remove stale index.lock if present ──────────────────────────────
$lockFile = Join-Path $RepoRoot ".git\index.lock"
if (Test-Path $lockFile) {
    Write-Host "`n[1/5] Removing stale .git/index.lock ..." -ForegroundColor Yellow
    Remove-Item $lockFile -Force
    Write-Host "      Lock removed." -ForegroundColor Green
} else {
    Write-Host "`n[1/5] No index.lock present -- OK" -ForegroundColor Green
}

# ── Step 2: Quick sanity check on index.html ────────────────────────────────
Write-Host "`n[2/5] Sanity-checking index.html ..." -ForegroundColor Yellow
$html = Get-Content "index.html" -Raw
if ($html -match "window\._v149AvgRisk\s*=\s*function") {
    Write-Host "      window._v149AvgRisk: DEFINED ✓" -ForegroundColor Green
} else {
    Write-Host "ERROR: window._v149AvgRisk NOT defined in index.html!" -ForegroundColor Red
    exit 1
}
if ($html -match "data\.items\|\|data\.advisories") {
    Write-Host "      _fetchLiveIntel data.items parser: PRESENT ✓" -ForegroundColor Green
} else {
    Write-Host "ERROR: data.items parser missing from index.html!" -ForegroundColor Red
    exit 1
}

# ── Step 3: Quick sanity check on v149_frontend_dedup_patch.py ──────────────
Write-Host "`n[3/5] Sanity-checking v149_frontend_dedup_patch.py ..." -ForegroundColor Yellow
python scripts\v149_frontend_dedup_patch.py --dry-run 2>&1 | Select-Object -First 10
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: v149_frontend_dedup_patch.py failed" -ForegroundColor Red
    exit 1
}
Write-Host "      Patch script: CLEAN ✓" -ForegroundColor Green

# ── Step 4: Stage files ──────────────────────────────────────────────────────
Write-Host "`n[4/5] Staging files ..." -ForegroundColor Yellow
$files = @(
    "index.html",
    "scripts/v149_frontend_dedup_patch.py"
)
foreach ($f in $files) {
    git add $f
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: git add $f failed" -ForegroundColor Red
        exit 1
    }
    Write-Host "      Staged: $f" -ForegroundColor Green
}

# ── Step 5: Commit + Push ────────────────────────────────────────────────────
Write-Host "`n[5/5] Committing + pushing ..." -ForegroundColor Yellow
$msg = @"
fix(v152.3): P0 AI Cyber Brain + APEX AI full fix -- REFRESH ANALYSIS + live intel

BUGS FIXED (4 total):

BUG #1 (P0) -- index.html line 5274: bare box-drawing SyntaxError
  ROOT CAUSE: v149_frontend_dedup_patch.py injected UNIFIED_RISK_JS using
  insert_after="// ── end v149 DEDUP GUARD ──" which matched only the first
  30 chars of the longer DEDUP_GUARD_JS end comment. The remaining
  ──────────────────────────────── chars were left as a bare JS statement
  inside <script>, causing a JavaScript SyntaxError. This prevented the
  entire script block from executing, so window._v149AvgRisk was never
  defined.
  SYMPTOM: "ERROR: window._v149AvgRisk is not a function" in the GENESIS
  REFRESH ANALYSIS button.
  FIX: Deleted the stray box-drawing line 5274.

BUG #2 (P0) -- scripts/v149_frontend_dedup_patch.py: permanent re-injection
  ROOT CAUSE: Same partial match would re-introduce the stray chars on every
  subsequent pipeline run that re-ran the dedup patch.
  FIX: Changed DEDUP_GUARD_JS end marker to plain ASCII [end-v149-dedup-guard].
  Backward-compat matching for legacy HTML with old box-drawing marker preserved
  via insert_after_old_full / insert_after_old_short fallback logic.

BUG #3 (P1) -- _fetchLiveIntel(): apex_v2 data never loaded
  ROOT CAUSE: Parser used data.advisories||data.data||data.feed||[] but
  api/apex_v2/priority.json and critical.json use the 'items' key.
  SYMPTOM: AI Brain panels show "Connecting to live threat feed..." forever
  even though apex_v2 files have 200+ entries.
  FIX: Added data.items as first fallback: data.items||data.advisories||...

BUG #4 (P2) -- runAIBrain(): status bar elements permanently showing —
  ROOT CAUSE: ai-bar-predicted (High-Risk 30d count) and ai-bar-lastrun
  (timestamp) were never populated by runAIBrain().
  FIX: Added txt('ai-bar-predicted',...) and txt('ai-bar-lastrun',...) calls.

VERIFIED:
  All 15 HTML integrity checks PASS
  v149_frontend_dedup_patch.py syntax CLEAN
  window._v149AvgRisk defined in script block
  data.items in _fetchLiveIntel parser chain
  ai-bar-predicted and ai-bar-lastrun wired
"@

git commit -m $msg
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: git commit failed" -ForegroundColor Red
    exit 1
}

git push origin HEAD
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: git push failed" -ForegroundColor Red
    exit 1
}

Write-Host "`n============================================================" -ForegroundColor Green
Write-Host " DONE -- AI Brain fixes committed and pushed." -ForegroundColor Green
Write-Host " Watch pipeline:" -ForegroundColor Green
Write-Host " https://github.com/cyberdudebivash/CYBERDUDEBIVASH-THREAT-INTEL-PLATFORM/actions" -ForegroundColor Cyan
Write-Host "============================================================`n" -ForegroundColor Green
