#!/usr/bin/env pwsh
# ============================================================
# SENTINEL APEX v148.0.0 — FINAL COMMIT & PUSH SCRIPT
# Generated by CyberDudeBivash AI Engine — 2026-05-12
# ============================================================
Set-Location "C:\Users\Administrator\Desktop\CYBERDUDEBIVASH-THREAT-INTEL-PLATFORM"

Write-Host "=== SENTINEL APEX v148.0.0 — FINAL PRODUCTION COMMIT ===" -ForegroundColor Cyan

# Step 0: Clear any stale git index lock
$lockFile = ".git\index.lock"
if (Test-Path $lockFile) {
    Write-Host "[CLEAN] Removing stale git index.lock..." -ForegroundColor Yellow
    Remove-Item $lockFile -Force
    Write-Host "[OK] Lock cleared." -ForegroundColor Green
}

# Step 1: Stage all changes
Write-Host "[STAGE] Staging all changes..." -ForegroundColor Yellow
git add `
  .github/workflows/generate-and-sync.yml `
  .github/workflows/sentinel-blogger.yml `
  index.html `
  scripts/run_pipeline.py `
  scripts/validate_monetization.py `
  scripts/daily_brief_generator.py `
  upgrade.html `
  version.json `
  "workers/intel-gateway/src/index.js" `
  "workers/intel-gateway/wrangler.toml" `
  "api/v1/intel/daily_brief_latest.pdf" `
  "api/v1/intel/daily_brief_meta.json" `
  COMMIT_V148_FIXES.ps1 `
  "SENTINEL-APEX-CEO-CTO-AUDIT-MONETIZATION-STRATEGY-2026.docx"

# Stage data/reports if it exists
if (Test-Path "data\reports") { git add "data/reports/" }

# Show staged files
Write-Host "`n[STAGED FILES]" -ForegroundColor Cyan
git status --short

# Step 2: Commit
$commitMsg = @"
feat(v148): complete monetization activation — daily brief, worker auth, source trust, upgrade.html

SENTINEL APEX v148.0.0 — Production Monetization Hardening

Changes:
- fix: version drift zero — wrangler.toml + index.html pinned to v148.0.0
- fix: risk score capped at 8.0 max for entries without CVE/KEV evidence
- feat: Stage 5.7 Monetization Integrity Gate wired into generate-and-sync.yml (HARD FAIL)
- feat: Cloudflare Worker API key authentication enforced on PRO+ endpoints
  - /api/v1/intel/apex.json     → Bearer token required (PRO+)
  - /api/v1/intel/ai_summary.json → Bearer token required (PRO+)
  - /api/v1/intel/daily_brief_latest.pdf → Bearer token required (PRO+)
  - /api/v1/intel/daily_brief_meta.json  → FREE (metadata only)
- feat: Source trust weights differentiated (CISA=0.98, Mandiant=0.98, Krebs=0.90, CyberNews=0.68)
- feat: upgrade.html Gumroad purchase buttons live (PRO/TEAM/ENTERPRISE)
- feat: daily_brief_generator.py — executive PDF threat brief from ai_summary.json
- feat: Stage 5.5 — Daily Brief Generator added to CI/CD pipeline
- feat: serveDailyBriefPDF() + serveDailyBriefMeta() Worker handlers
- fix: validate_monetization.py 57-check gate — 0 failures, 0 warnings
- docs: SENTINEL-APEX-CEO-CTO-AUDIT-MONETIZATION-STRATEGY-2026.docx

Revenue readiness:
- Gumroad PRO/TEAM/ENTERPRISE products linked on upgrade.html
- Daily Brief PDF at \$9.99/mo — AI content pipeline fully automated
- API auth enforced — free-tier field masking active (25-item cap)
- Monetization gate blocks CI if revenue stack degrades

Validation: 57/57 checks PASS | AST clean | YAML valid | PDF 8KB valid
"@

Write-Host "`n[COMMIT] Writing commit..." -ForegroundColor Yellow
git commit -m $commitMsg

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Commit failed. Check git status above." -ForegroundColor Red
    exit 1
}

Write-Host "`n[COMMIT OK]" -ForegroundColor Green

# Step 3: Push with retry
Write-Host "`n[PUSH] Pushing to origin/main..." -ForegroundColor Yellow
$maxRetries = 3
$attempt = 0
do {
    $attempt++
    Write-Host "  Push attempt $attempt/$maxRetries..." -ForegroundColor Gray
    git push origin main 2>&1
    if ($LASTEXITCODE -eq 0) { break }
    if ($attempt -lt $maxRetries) {
        Write-Host "  Push failed, pulling and retrying..." -ForegroundColor Yellow
        git pull --rebase origin main
    }
} while ($attempt -lt $maxRetries)

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n======================================================" -ForegroundColor Green
    Write-Host "  SENTINEL APEX v148.0.0 — PUSHED TO ORIGIN/MAIN" -ForegroundColor Green
    Write-Host "  Monetization stack LIVE. Revenue engine ACTIVE." -ForegroundColor Green
    Write-Host "======================================================" -ForegroundColor Green
    git log --oneline -5
} else {
    Write-Host "`n[PUSH FAILED after $maxRetries attempts]" -ForegroundColor Red
    Write-Host "Run manually: git push origin main" -ForegroundColor Yellow
}
