name = "sentinel-apex-swarm-live"
main = "src/index.js"
compatibility_date = "2026-09-17"
workers_dev = false

routes = [
  { pattern = "intel.cyberdudebivash.com/api/swarm/*", zone_name = "cyberdudebivash.com" },
  { pattern = "intel.cyberdudebivash.com/swarm/*", zone_name = "cyberdudebivash.com" }
]

[vars]
CANONICAL_BASE_URL = "https://intel.cyberdudebivash.com"
SWARM_VERSION = "4.44.0"
SWARM_PROTOCOL = "cdb.swarm.v1"
