apiVersion: v2
name: sentinel-apex
description: CYBERDUDEBIVASH(R) SENTINEL APEX  -  AI-Native Cyber Intelligence Infrastructure Platform
type: application
version: 2.0.0
appVersion: "2.0.0"

home: https://intel.cyberdudebivash.com
sources:
  - https://github.com/cyberdudebivash/CYBERDUDEBIVASH-THREAT-INTEL-PLATFORM

maintainers:
  - name: CYBERDUDEBIVASH
    email: bivash@cyberdudebivash.com
    url: https://cyberdudebivash.com

keywords:
  - cybersecurity
  - threat-intelligence
  - cti
  - ai-security
  - soc-automation
  - zero-trust

dependencies:
  - name: postgresql
    version: "14.3.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "19.5.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "29.3.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: keycloak
    version: "21.4.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: grafana
    version: "7.3.9"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: prometheus
    version: "25.20.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
