"""
CyberDudeBivash Weekly Top Exploited CVEs Mega-Report
FINAL • PRODUCTION • AUTHORITY-GRADE
"""

from datetime import datetime, timezone
from typing import List, Dict


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def format_weekly_cve_report(
    ranked_cves: List[Dict],
    author: str,
    site_url: str,
) -> str:
    sections: List[str] = []

    # -------------------------------------------------
    # HEADER
    # -------------------------------------------------
    sections.append(f"""
<h2>Weekly Top Exploited CVEs – Cyber Threat Intelligence Mega-Report</h2>
<p>
<strong>Reporting Window:</strong> Last 7 Days<br>
<strong>Published:</strong> {_utc_now()}<br>
<strong>Prepared By:</strong> {author}
</p>
""")

    # -------------------------------------------------
    # EXECUTIVE OVERVIEW
    # -------------------------------------------------
    sections.append("""
<h3>Executive Threat Overview</h3>
<p>
This weekly mega-report identifies the most operationally dangerous vulnerabilities
observed over the past seven days. Rankings are based on exploitation probability,
confirmed in-the-wild activity, and adversary preference indicators rather than
severity scores alone.
</p>
<p>
The findings reflect attacker emphasis on scalable, reliable exploitation paths
that enable rapid initial access and follow-on intrusion activity.
</p>
""")

    # -------------------------------------------------
    # RANKED CVES
    # -------------------------------------------------
    if not ranked_cves:
        sections.append("""
<p>
No high-confidence exploited CVEs met the ranking threshold this week.
This does not indicate reduced threat activity, but rather a temporary shift
in adversary focus.
</p>
""")
    else:
        for idx, cve in enumerate(ranked_cves, start=1):
            sections.append(f"""
<h3>{idx}. {cve.get('id')} — Risk Score: {cve.get('risk_score')}</h3>
<p>
<strong>Severity:</strong> {cve.get('severity')} |
<strong>CVSS:</strong> {cve.get('cvss')} |
<strong>EPSS:</strong> {round(cve.get('epss', 0.0), 3)} |
<strong>CISA KEV:</strong> {"Yes" if cve.get("is_kev") else "No"}
</p>

<p>
This vulnerability demonstrated elevated exploitation risk during the reporting
period. Indicators suggest active scanning, exploit testing, or integration into
broader attack campaigns.
</p>

<p>
Organizations operating affected systems should treat this vulnerability as a
priority candidate for remediation and defensive validation.
</p>
""")

    # -------------------------------------------------
    # STRATEGIC TAKEAWAYS
    # -------------------------------------------------
    sections.append(f"""
<h3>Strategic Defender Takeaways</h3>
<p>
This week’s data reinforces a recurring trend: attackers consistently prioritize
reliable exploitation opportunities over novel techniques. Defensive success
depends on disciplined patch management, behavior-based detections, and continuous
risk-informed prioritization.
</p>

<h3>CyberDudeBivash Intelligence Note</h3>
<p>
This report was generated by the CyberDudeBivash Threat Intelligence Platform using
automated risk scoring, exploitation trend analysis, and adversary behavior
correlation.
</p>
<p>
Explore more intelligence at <a href="{site_url}">{site_url}</a>
</p>
""")

    return "\n".join(sections)
