"""
SENTINEL APEX v27.0 — SIEM Query Generators
=============================================
Generates native SIEM queries for various platforms.

Supported:
- KQL (Microsoft Sentinel / Azure Monitor)
- SPL (Splunk)
- EQL (Elastic)

(c) 2026 CyberDudeBivash Pvt. Ltd. All Rights Reserved.
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional, Any

from .generator import (
    BaseRuleGenerator,
    GeneratedRule,
    RuleType,
    RuleConfidence,
)


class KQLGenerator(BaseRuleGenerator):
    """
    Generates KQL queries for Microsoft Sentinel.
    """
    
    RULE_TYPE = RuleType.KQL
    
    def generate(
        self,
        threat_data: Dict[str, Any],
        iocs: Optional[List[Dict]] = None,
    ) -> Optional[GeneratedRule]:
        """Generate KQL query from threat data"""
        
        title = threat_data.get("title", "Unknown Threat")
        description = threat_data.get("description", "")
        severity = threat_data.get("severity", "medium")
        mitre_techniques = threat_data.get("mitre_techniques", [])
        
        # Extract IOCs
        extracted_iocs = self._extract_iocs_from_text(description)
        
        if not any(extracted_iocs.values()):
            return None
        
        rule_id = self._generate_rule_id(title)
        
        # Build KQL query
        query = self._build_kql_query(extracted_iocs, title, description)
        
        if not query:
            return None
        
        # Add header comment
        content = f"""// {title}
// Generated by CyberDudeBivash SENTINEL APEX v27.0
// Date: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
// Rule ID: {rule_id}
// MITRE: {', '.join(mitre_techniques[:3]) if mitre_techniques else 'N/A'}

{query}"""
        
        ioc_count = sum(len(v) for v in extracted_iocs.values())
        confidence = self._determine_confidence(
            ioc_count, len(mitre_techniques) > 0, False
        )
        
        return GeneratedRule(
            rule_id=rule_id,
            rule_type=RuleType.KQL,
            name=title,
            description=description[:200],
            content=content,
            confidence=confidence,
            severity=severity,
            mitre_techniques=mitre_techniques,
            iocs_used=[k for k, v in extracted_iocs.items() if v],
            source_threat=threat_data.get("id"),
        )
    
    def validate(self, rule: GeneratedRule) -> bool:
        """Basic KQL syntax validation"""
        content = rule.content
        
        # Check for common KQL elements
        if not any(kw in content for kw in ["where", "project", "summarize", "|"]):
            return False
        
        return True
    
    def _build_kql_query(
        self,
        iocs: Dict[str, List[str]],
        title: str,
        description: str
    ) -> Optional[str]:
        """Build KQL query from IOCs"""
        
        conditions = []
        tables_used = set()
        
        # Network IOCs
        if iocs.get("ip"):
            ips = iocs["ip"][:10]
            ip_list = ", ".join(f'"{ip}"' for ip in ips)
            conditions.append(f"RemoteIP in ({ip_list}) or DestinationIP in ({ip_list})")
            tables_used.add("CommonSecurityLog")
        
        if iocs.get("domain"):
            domains = iocs["domain"][:10]
            domain_list = ", ".join(f'"{d}"' for d in domains)
            conditions.append(f"RemoteDnsName has_any ({domain_list})")
            tables_used.add("DnsEvents")
        
        if iocs.get("url"):
            urls = iocs["url"][:5]
            for url in urls:
                conditions.append(f'Url contains "{url}"')
            tables_used.add("CommonSecurityLog")
        
        # File hashes
        if iocs.get("md5") or iocs.get("sha256"):
            hashes = (iocs.get("md5", []) + iocs.get("sha256", []))[:10]
            hash_list = ", ".join(f'"{h.lower()}"' for h in hashes)
            conditions.append(f"FileHash in ({hash_list})")
            tables_used.add("DeviceFileEvents")
        
        if not conditions:
            return None
        
        # Build query
        primary_table = list(tables_used)[0] if tables_used else "CommonSecurityLog"
        condition_str = "\n    or ".join(conditions)
        
        query = f"""{primary_table}
| where {condition_str}
| project TimeGenerated, DeviceName, AccountName, RemoteIP, FileName, FileHash
| extend AlertTitle = "{title}"
| order by TimeGenerated desc
| take 100"""
        
        return query


class SPLGenerator(BaseRuleGenerator):
    """
    Generates SPL queries for Splunk.
    """
    
    RULE_TYPE = RuleType.SPL
    
    def generate(
        self,
        threat_data: Dict[str, Any],
        iocs: Optional[List[Dict]] = None,
    ) -> Optional[GeneratedRule]:
        """Generate SPL query from threat data"""
        
        title = threat_data.get("title", "Unknown Threat")
        description = threat_data.get("description", "")
        severity = threat_data.get("severity", "medium")
        mitre_techniques = threat_data.get("mitre_techniques", [])
        
        extracted_iocs = self._extract_iocs_from_text(description)
        
        if not any(extracted_iocs.values()):
            return None
        
        rule_id = self._generate_rule_id(title)
        
        query = self._build_spl_query(extracted_iocs, title)
        
        if not query:
            return None
        
        content = f"""`comment("
Title: {title}
Generated by: CyberDudeBivash SENTINEL APEX v27.0
Date: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
Rule ID: {rule_id}
MITRE: {', '.join(mitre_techniques[:3]) if mitre_techniques else 'N/A'}
")`
{query}"""
        
        ioc_count = sum(len(v) for v in extracted_iocs.values())
        confidence = self._determine_confidence(
            ioc_count, len(mitre_techniques) > 0, False
        )
        
        return GeneratedRule(
            rule_id=rule_id,
            rule_type=RuleType.SPL,
            name=title,
            description=description[:200],
            content=content,
            confidence=confidence,
            severity=severity,
            mitre_techniques=mitre_techniques,
            iocs_used=[k for k, v in extracted_iocs.items() if v],
            source_threat=threat_data.get("id"),
        )
    
    def validate(self, rule: GeneratedRule) -> bool:
        """Basic SPL syntax validation"""
        content = rule.content
        
        # Check for common SPL elements
        if not any(kw in content for kw in ["index=", "|", "search", "stats"]):
            return False
        
        return True
    
    def _build_spl_query(
        self,
        iocs: Dict[str, List[str]],
        title: str
    ) -> Optional[str]:
        """Build SPL query from IOCs"""
        
        conditions = []
        
        # Network IOCs
        if iocs.get("ip"):
            ips = " OR ".join(f'dest_ip="{ip}"' for ip in iocs["ip"][:10])
            conditions.append(f"({ips})")
        
        if iocs.get("domain"):
            domains = " OR ".join(f'query=*{d}*' for d in iocs["domain"][:10])
            conditions.append(f"({domains})")
        
        # Hashes
        if iocs.get("md5"):
            hashes = " OR ".join(f'file_hash="{h}"' for h in iocs["md5"][:5])
            conditions.append(f"({hashes})")
        
        if iocs.get("sha256"):
            hashes = " OR ".join(f'file_hash="{h}"' for h in iocs["sha256"][:5])
            conditions.append(f"({hashes})")
        
        if not conditions:
            return None
        
        condition_str = " OR ".join(conditions)
        
        query = f"""index=* sourcetype=*
({condition_str})
| stats count by src_ip, dest_ip, user, file_name, file_hash
| eval alert_name="{title}"
| sort -count"""
        
        return query


class EQLGenerator(BaseRuleGenerator):
    """
    Generates EQL queries for Elastic Security.
    """
    
    RULE_TYPE = RuleType.EQL
    
    def generate(
        self,
        threat_data: Dict[str, Any],
        iocs: Optional[List[Dict]] = None,
    ) -> Optional[GeneratedRule]:
        """Generate EQL query from threat data"""
        
        title = threat_data.get("title", "Unknown Threat")
        description = threat_data.get("description", "")
        severity = threat_data.get("severity", "medium")
        mitre_techniques = threat_data.get("mitre_techniques", [])
        
        extracted_iocs = self._extract_iocs_from_text(description)
        
        if not any(extracted_iocs.values()):
            return None
        
        rule_id = self._generate_rule_id(title)
        
        query = self._build_eql_query(extracted_iocs, description)
        
        if not query:
            return None
        
        content = f"""/*
Title: {title}
Generated by: CyberDudeBivash SENTINEL APEX v27.0
Date: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
Rule ID: {rule_id}
MITRE: {', '.join(mitre_techniques[:3]) if mitre_techniques else 'N/A'}
*/

{query}"""
        
        ioc_count = sum(len(v) for v in extracted_iocs.values())
        confidence = self._determine_confidence(
            ioc_count, len(mitre_techniques) > 0, False
        )
        
        return GeneratedRule(
            rule_id=rule_id,
            rule_type=RuleType.EQL,
            name=title,
            description=description[:200],
            content=content,
            confidence=confidence,
            severity=severity,
            mitre_techniques=mitre_techniques,
            iocs_used=[k for k, v in extracted_iocs.items() if v],
            source_threat=threat_data.get("id"),
        )
    
    def validate(self, rule: GeneratedRule) -> bool:
        """Basic EQL syntax validation"""
        content = rule.content
        
        # Check for EQL event types
        if not any(et in content for et in ["process", "network", "file", "dns", "any"]):
            return False
        
        return True
    
    def _build_eql_query(
        self,
        iocs: Dict[str, List[str]],
        description: str
    ) -> Optional[str]:
        """Build EQL query from IOCs"""
        
        # Determine event type based on IOCs
        if iocs.get("ip") or iocs.get("domain"):
            return self._build_network_eql(iocs)
        elif iocs.get("md5") or iocs.get("sha256"):
            return self._build_file_eql(iocs)
        
        return None
    
    def _build_network_eql(self, iocs: Dict) -> str:
        """Build network-based EQL query"""
        conditions = []
        
        if iocs.get("ip"):
            ips = ", ".join(f'"{ip}"' for ip in iocs["ip"][:10])
            conditions.append(f"destination.ip in ({ips})")
        
        if iocs.get("domain"):
            for domain in iocs["domain"][:5]:
                conditions.append(f'dns.question.name : "*{domain}*"')
        
        condition_str = " or ".join(conditions)
        
        return f"""network where {condition_str}"""
    
    def _build_file_eql(self, iocs: Dict) -> str:
        """Build file-based EQL query"""
        hashes = []
        
        if iocs.get("md5"):
            hashes.extend(iocs["md5"][:5])
        if iocs.get("sha256"):
            hashes.extend(iocs["sha256"][:5])
        
        hash_list = ", ".join(f'"{h.lower()}"' for h in hashes)
        
        return f"""file where file.hash.sha256 in ({hash_list}) or file.hash.md5 in ({hash_list})"""


__all__ = ["KQLGenerator", "SPLGenerator", "EQLGenerator"]
