#!/usr/bin/env python3
"""
Build workers/intel-gateway/src/attack-technique-tactics.js from the repo's
MITRE ATT&CK reference sync (data/attck/enterprise-attack.json, written by
scripts/true_intel_ingestor.py:sync_mitre_attack).

The Worker cannot read the 1.1 MB reference at request time, so it ships a
compact technique -> tactic-id table generated from it. The table is the
reference, not an opinion: every entry comes from the technique's own
"tactics" field. Sub-techniques are folded into their parent only when the
reference gives them the same tactics (true for every sub-technique today);
any that differ are kept as explicit entries.

    python3 scripts/build_attack_tactic_map.py          # write
    python3 scripts/build_attack_tactic_map.py --check  # exit 1 on drift

workers/intel-gateway/src/__tests__/dashboard-contract.test.js recomputes the
table from the reference and fails when the committed module is stale.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "data" / "attck" / "enterprise-attack.json"
OUTPUT = ROOT / "workers" / "intel-gateway" / "src" / "attack-technique-tactics.js"


def build_table(ref: dict) -> dict:
    tactic_id = {t["shortname"]: t["attck_id"] for t in ref["tactics"]}
    by_tech = {}
    for t in ref["techniques"]:
        ids = sorted({tactic_id[s] for s in t.get("tactics", []) if s in tactic_id})
        if ids:
            by_tech[t["attck_id"]] = ids
    table = {}
    for tid in sorted(by_tech):
        parent = tid.split(".")[0]
        if "." in tid and by_tech.get(parent) == by_tech[tid]:
            continue
        table[tid] = by_tech[tid]
    return table


def render(ref: dict) -> str:
    table = build_table(ref)
    tactics = sorted((t["attck_id"], t["name"]) for t in ref["tactics"])
    lines = [
        "// GENERATED by scripts/build_attack_tactic_map.py from data/attck/enterprise-attack.json.",
        "// Do not edit by hand: rerun the script after the reference sync changes.",
        "",
        "export const ATTACK_REFERENCE = Object.freeze(" + json.dumps({
            "source": ref.get("source"),
            "source_bundle": ref.get("source_bundle"),
            "synced_at": ref.get("synced_at"),
            "content_hash": ref.get("content_hash"),
            "techniques": len(ref["techniques"]),
            "tactics": len(ref["tactics"]),
        }, sort_keys=True) + ");",
        "",
        "/** Reference tactic id -> name. */",
        "export const REFERENCE_TACTICS = Object.freeze(" + json.dumps(dict(tactics)) + ");",
        "",
        "/**",
        " * Technique id -> reference tactic ids. A sub-technique missing here has",
        " * its parent's tactics (the reference gives them identical tactics).",
        " */",
        "export const TECHNIQUE_TACTIC_IDS = Object.freeze({",
    ]
    for tid, ids in table.items():
        lines.append("  " + json.dumps(tid) + ": " + json.dumps(ids) + ",")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def main(argv) -> int:
    ref = json.loads(REFERENCE.read_text(encoding="utf-8"))
    text = render(ref)
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"DRIFT: {OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/build_attack_tactic_map.py")
            return 1
        print("OK: attack-technique-tactics.js matches the reference")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(build_table(ref))} technique entries, {len(ref['tactics'])} tactics")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
