#!/usr/bin/env python3
"""
SENTINEL APEX — Detection Quality Engine v1.0.0
Validates Sigma, YARA, Suricata, KQL. Rejects generic rules.
Marks generic rules as DETECTION_NOT_PRODUCTION_READY.
"""
from __future__ import annotations
import argparse, json, logging, re, sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ENGINE_VERSION = "1.0.0"
REPO_ROOT = Path(__file__).resolve().parent.parent
logging.basicConfig(level=logging.INFO,
    format="%(asctime)s [detection-quality] %(levelname)s: %(message)s")
log = logging.getLogger(__name__)

SIGMA_GENERIC = [
    r"Class:\s*GENERIC",r"product:\s*generic",r"category:\s*network_connection\b",
    r"EventID.*4625.*4648.*4728",r"LogonType:\s*3",
    r"status:\s*experimental.*GENERIC",r"Generated by.*APEX.*GENERIC",
    r"source\s+SENTINEL-APEX.*GENERIC",
]
SURICATA_GENERIC = [
    r"\|90\s+90\s+90\s+90\|",r"msg:.*GENERIC",
    r"threshold:.*type threshold.*track by_src.*count 3.*seconds 60",
]
KQL_GENERIC = [
    r"//\s*GENERIC",r"EventID\s+in\s+\(4625\s*,\s*4648\s*,\s*4728\)",
]
SIGMA_SPECIFIC = [
    r"CVE-\d{4}-\d+",r"CommandLine\|",r"Image\|",r"TargetFilename\|",
    r"RegistryKey|RegistryValue",r"DestinationHostname\|contains",
    r"DestinationIp\|",r"Hash\|",r"User-Agent\|contains",r"status:\s*(stable|test)",
]
SURICATA_SPECIFIC = [
    r'content:"[A-Za-z0-9/\-_\.]{8,}"',r"pcre:\"/.{8,}/",
    r"http\.uri\s*;",r"http\.header\s*;",r"tls\.sni\s*;",
    r"dns\.query\s*;",r"CVE-\d{4}-\d+",r"file\.data\s*;",
]
KQL_SPECIFIC = [
    r"ProcessCommandLine\s+contains",r"SHA256Hash\s*==",
    r"RemoteIPType\s*==",r"FileHash\s*==",r"CVE-\d{4}-\d+",
]


def _matches_any(text: str, patterns: List[str]) -> Optional[str]:
    for p in patterns:
        if re.search(p, text, re.I|re.DOTALL): return p
    return None


def validate_sigma_rule(rule: str, item: Dict) -> Dict:
    if not rule or len(rule.strip()) < 20:
        return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"empty or trivial","production_ready":False}
    g = _matches_any(rule, SIGMA_GENERIC)
    if g: return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":f"generic: {g[:60]}","production_ready":False}
    s = _matches_any(rule, SIGMA_SPECIFIC)
    if s: return {"status":"DETECTION_PRODUCTION_READY","reason":f"specific artifact: {s[:60]}","production_ready":True}
    cve = item.get("cve_id") or ""
    if cve and cve in rule:
        return {"status":"DETECTION_CVE_SPECIFIC","reason":f"references {cve}","production_ready":True}
    return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"no specific artifact","production_ready":False}


def validate_suricata_rule(rule: str, item: Dict) -> Dict:
    if not rule or len(rule.strip()) < 20:
        return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"empty","production_ready":False}
    g = _matches_any(rule, SURICATA_GENERIC)
    if g: return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":f"generic: {g[:60]}","production_ready":False}
    s = _matches_any(rule, SURICATA_SPECIFIC)
    if s: return {"status":"DETECTION_PRODUCTION_READY","reason":f"specific content: {s[:60]}","production_ready":True}
    cve = item.get("cve_id") or ""
    if cve and cve in rule:
        return {"status":"DETECTION_CVE_SPECIFIC","reason":f"references {cve}","production_ready":True}
    return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"no specific content match","production_ready":False}


def validate_kql(kql: str, item: Dict) -> Dict:
    if not kql or len(kql.strip()) < 10:
        return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"empty","production_ready":False}
    g = _matches_any(kql, KQL_GENERIC)
    if g: return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":f"generic: {g[:60]}","production_ready":False}
    s = _matches_any(kql, KQL_SPECIFIC)
    if s: return {"status":"DETECTION_PRODUCTION_READY","reason":f"specific: {s[:60]}","production_ready":True}
    return {"status":"DETECTION_NOT_PRODUCTION_READY","reason":"no specific artifact","production_ready":False}


def assess_item_detections(item: Dict) -> Tuple[Dict, Dict]:
    item = dict(item)
    results = {}; production_count = 0; total_rules = 0
    if item.get("sigma_rule"):
        total_rules += 1; r = validate_sigma_rule(item["sigma_rule"], item)
        results["sigma"] = r
        if r["production_ready"]: production_count += 1
    if item.get("suricata_rule"):
        total_rules += 1; r = validate_suricata_rule(item["suricata_rule"], item)
        results["suricata"] = r
        if r["production_ready"]: production_count += 1
    if item.get("kql_query"):
        total_rules += 1; r = validate_kql(item["kql_query"], item)
        results["kql"] = r
        if r["production_ready"]: production_count += 1
    if item.get("yara_rule"):
        total_rules += 1
        has_specific = bool(re.search(r'strings:\s*\n.*\$\w+\s*=\s*"[^"]{6,}"',item["yara_rule"],re.DOTALL))
        r = {"status":"DETECTION_PRODUCTION_READY" if has_specific else "DETECTION_NOT_PRODUCTION_READY",
             "reason":"has specific string" if has_specific else "no specific string","production_ready":has_specific}
        results["yara"] = r
        if has_specific: production_count += 1
    overall = ("DETECTION_PRODUCTION_READY" if production_count == total_rules and total_rules > 0
               else "DETECTION_PARTIALLY_READY" if production_count > 0
               else "DETECTION_NOT_PRODUCTION_READY")
    item["detection_quality_status"] = overall
    item["detection_production_ready"] = production_count > 0
    item["detection_rules_total"] = total_rules
    item["detection_rules_production_ready"] = production_count
    return {"id":item.get("id",""),"title":(item.get("title") or "")[:60],
            "detection_quality_status":overall,"production_ready_count":production_count,
            "total_rules":total_rules,"rule_results":results}, item


def process_feed(items: List[Dict]) -> Tuple[List[Dict], Dict]:
    governed, assessments = [], []
    ready, partial, not_ready, no_rules = 0, 0, 0, 0
    for item in items:
        record, patched = assess_item_detections(item)
        governed.append(patched); assessments.append(record)
        status = record["detection_quality_status"]
        if record["total_rules"] == 0: no_rules += 1
        elif status == "DETECTION_PRODUCTION_READY": ready += 1
        elif status == "DETECTION_PARTIALLY_READY": partial += 1
        else: not_ready += 1
    return governed, {
        "total_items":len(items),"production_ready":ready,"partially_ready":partial,
        "not_production_ready":not_ready,"no_detection_rules":no_rules,
        "deployable_detection_items":ready+partial,"per_item":assessments,
        "engine_version":ENGINE_VERSION,"generated_at":datetime.now(timezone.utc).isoformat(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Detection Quality Engine v{ENGINE_VERSION}")
    parser.add_argument("feed", nargs="?", default=str(REPO_ROOT/"api"/"feed.json"))
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--output", default=str(REPO_ROOT/"api"/"detection_quality.json"))
    args = parser.parse_args()
    raw = Path(args.feed).read_bytes().rstrip(b"\x00")
    data = json.loads(raw)
    items = data if isinstance(data,list) else data.get("threats",data.get("items",[]))
    log.info("[detection-quality] Processing %d items", len(items))
    governed, summary = process_feed(items)
    log.info("[detection-quality] ready=%d partial=%d not_ready=%d no_rules=%d",
             summary["production_ready"],summary["partially_ready"],
             summary["not_production_ready"],summary["no_detection_rules"])
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    if args.apply:
        Path(args.feed).write_text(json.dumps(governed, indent=2, ensure_ascii=False), encoding="utf-8")
        log.info("[detection-quality] Governed feed written to %s", args.feed)
    return 0

if __name__ == "__main__":
    sys.exit(main())
