#!/usr/bin/env python3
"""
SENTINEL APEX v171.3 -- Production Release Gates (STAGE 5.9.2)
RC-GATE-2 FIX v171.3: Recalibrated thresholds to match incremental pipeline runs.
  - GATE-1/GATE-3 thresholds lowered: 100/50 -> 5 (catches truly empty feeds,
    not normal run-size variation; pipeline generates 10-200 items per incremental run).
  - GATE-4 repointed: static root feed_manifest.json (stale 190) -> runtime
    api/feed.json vs api/latest.json drift (both pipeline-generated each run).
ANY failure = deployment BLOCKED (exits 1).

Gates:
  1. api/feed.json exists with count >= 5
  2. api/reports/index.json exists with total_reports > 0
  3. api/latest.json exists with count >= 5
  4. api/feed.json vs api/latest.json drift <= 50% (endpoint consistency)
  5. version.json readable with version field
"""
import json
import sys
import pathlib

REPO = pathlib.Path(__file__).parent.parent
errors = []
warnings = []

print("=" * 60)
print("SENTINEL APEX v171.3 - PRODUCTION RELEASE GATES")
print("=" * 60)

# GATE 1: api/feed.json exists with count >= 5
# Note: api/feed.json is runtime-generated (gitignored); count varies by run (10-200).
# Threshold=5 catches truly empty/failed pipeline runs without false-positives
# on normal incremental runs.
feed_path = REPO / "api" / "feed.json"
feed_count = 0
if not feed_path.exists():
    errors.append("GATE-1 FAIL: api/feed.json does not exist (pipeline did not generate data)")
else:
    try:
        d = json.loads(feed_path.read_text(encoding="utf-8"))
        items = d if isinstance(d, list) else d.get("items", d.get("data", []))
        feed_count = len(items)
        print(f"GATE-1: api/feed.json items={feed_count}")
        if feed_count < 5:
            errors.append(
                f"GATE-1 FAIL: api/feed.json has {feed_count} items (min 5 -- "
                "pipeline produced empty or near-empty feed)"
            )
        else:
            print("GATE-1: PASS")
    except Exception as e:
        errors.append(f"GATE-1 FAIL: api/feed.json parse error: {e}")

# GATE 2: api/reports/index.json exists with total_reports > 0
reports_path = REPO / "api" / "reports" / "index.json"
if not reports_path.exists():
    errors.append("GATE-2 FAIL: api/reports/index.json missing")
else:
    try:
        d = json.loads(reports_path.read_text(encoding="utf-8"))
        total = d.get("total_reports", 0)
        print(f"GATE-2: api/reports/index.json total_reports={total}")
        if total == 0:
            errors.append("GATE-2 FAIL: total_reports=0")
        else:
            print("GATE-2: PASS")
    except Exception as e:
        errors.append(f"GATE-2 FAIL: api/reports/index.json parse error: {e}")

# GATE 3: api/latest.json exists with count >= 5
# Note: api/latest.json is regenerated each run; threshold=5 catches empty outputs.
latest_path = REPO / "api" / "latest.json"
latest_count = 0
if not latest_path.exists():
    errors.append("GATE-3 FAIL: api/latest.json does not exist")
else:
    try:
        d = json.loads(latest_path.read_text(encoding="utf-8"))
        latest_count = d.get("count", 0) if isinstance(d, dict) else len(d)
        print(f"GATE-3: api/latest.json count={latest_count}")
        if latest_count < 5:
            errors.append(
                f"GATE-3 FAIL: api/latest.json has {latest_count} items (min 5 -- "
                "pipeline produced empty or near-empty latest endpoint)"
            )
        else:
            print("GATE-3: PASS")
    except Exception as e:
        errors.append(f"GATE-3 FAIL: api/latest.json parse error: {e}")

# GATE 4: API endpoint consistency check
# Compares api/feed.json vs api/latest.json (both runtime-generated by the same pipeline).
# Drift > 50% indicates a generation failure in one endpoint.
# RC-GATE-2 FIX v171.3: Removed comparison against static root feed_manifest.json
# (manually set to count=190, always diverged from runtime feed counts).
if feed_count > 0 and latest_count > 0:
    drift = abs(feed_count - latest_count) / max(feed_count, latest_count)
    print(f"GATE-4: feed={feed_count} latest={latest_count} drift={drift:.1%}")
    if drift > 0.50:
        errors.append(
            f"GATE-4 FAIL: api/feed.json ({feed_count}) vs api/latest.json ({latest_count}) "
            f"drift {drift:.1%} > 50% -- API endpoint inconsistency detected"
        )
    else:
        print(f"GATE-4: PASS (drift {drift:.1%})")
elif feed_count == 0 and latest_count == 0:
    warnings.append("GATE-4 SKIP: both feed and latest empty (covered by GATE-1 and GATE-3)")
else:
    warnings.append(f"GATE-4 WARN: feed={feed_count} latest={latest_count} -- one endpoint empty")

# GATE 5: version.json readable with version field
ver_path = REPO / "version.json"
if not ver_path.exists():
    errors.append("GATE-5 FAIL: version.json missing")
else:
    try:
        d = json.loads(ver_path.read_text(encoding="utf-8"))
        ver = d.get("version", "")
        print(f"GATE-5: version.json version={ver}")
        if not ver:
            errors.append("GATE-5 FAIL: no version field")
        else:
            print("GATE-5: PASS")
    except Exception as e:
        errors.append(f"GATE-5 FAIL: version.json parse error: {e}")

print()
print("=" * 60)
for w in warnings:
    print(f"  WARN: {w}")
if errors:
    print(f"RELEASE GATE: BLOCKED ({len(errors)} failures)")
    for e in errors:
        print(f"  FAIL: {e}")
    print("=" * 60)
    sys.exit(1)
else:
    print("RELEASE GATE: CERTIFIED -- all 5 gates passed")
    print("=" * 60)
