#!/usr/bin/env python3
"""
scripts/sync_report_urls.py
===============================================================================
CYBERDUDEBIVASH(R) SENTINEL APEX v161.2 -- Report URL Sync Engine
===============================================================================
P0 PERMANENT MANDATE: Every intel report generated by the platform MUST be
linked in api/feed.json so the dashboard and API expose real report links.

ROOT CAUSE FIXED HERE:
  generate_intel_reports.py writes report_url → data/stix/feed_manifest.json
  api/feed.json is NEVER updated with report_url → dashboard shows ⚠ NO DOSSIER

THIS SCRIPT:
  1. Reads data/stix/feed_manifest.json (where generate_intel_reports.py writes)
  2. Reads api/feed.json (what the dashboard and API serve)
  3. For each item: syncs report_url, internal_report_url, validation_status
     Matching key: item["id"]
  4. Fallback: scans reports/ directory on disk for matching file by id + timestamp
  5. Atomic write → api/feed.json (tmp + os.replace, never partial)
  6. Also updates api/latest.json if present

Strategy:
  - NEVER clears an existing valid report_url
  - NEVER sets report_url to a non-existent path (disk-verified optional)
  - Always makes URLs absolute (https://intel.cyberdudebivash.com/...)
  - Non-fatal: any item-level error is logged and skipped, pipeline continues

INSERTION POINT: sentinel-blogger.yml STAGE 3.1.7 (after STAGE 3.1.6)
MUST RUN: after run_pipeline.py (Stage 3.6 generates reports + sets report_url
           in feed_manifest.json) and before the git commit stage.

(c) 2026 CyberDudeBivash Pvt. Ltd. All Rights Reserved. CONFIDENTIAL.
===============================================================================
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
REPO_ROOT    = Path(__file__).resolve().parent.parent
FEED_MANIFEST = REPO_ROOT / "data" / "stix" / "feed_manifest.json"
API_FEED      = REPO_ROOT / "api" / "feed.json"
LATEST_JSON   = REPO_ROOT / "api" / "latest.json"
REPORTS_ROOT  = REPO_ROOT / "reports"
BASE_URL      = os.environ.get("PLATFORM_BASE_URL", "https://intel.cyberdudebivash.com")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [sync-report-urls] %(levelname)s: %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
    stream=sys.stdout,
)
log = logging.getLogger("sync_report_urls")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _load_json_safe(path: Path) -> Any:
    """Load JSON from path with encoding fallback. Returns None on failure."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        log.warning("Failed to load %s: %s", path, e)
        return None


def _atomic_write(path: Path, data: Any, indent: int = 2) -> bool:
    """Atomic JSON write via tmp + os.replace. Returns True on success."""
    tmp = path.with_suffix(".sync_tmp")
    try:
        tmp.write_text(
            json.dumps(data, indent=indent, ensure_ascii=False, default=str),
            encoding="utf-8"
        )
        os.replace(tmp, path)
        return True
    except Exception as e:
        log.error("Atomic write failed for %s: %s", path, e)
        if tmp.exists():
            try:
                tmp.unlink()
            except Exception:
                pass
        return False


def _make_absolute_url(url: str) -> str:
    """Ensure report_url is absolute. Handles relative /reports/... paths."""
    if not url:
        return ""
    if url.startswith("http://") or url.startswith("https://"):
        # Normalize old domain if needed
        return url.replace(
            "https://reports.cyberdudebivash.com",
            BASE_URL
        ).replace(
            "http://intel.cyberdudebivash.com",
            BASE_URL
        )
    if url.startswith("/"):
        return BASE_URL.rstrip("/") + url
    return url


def _is_valid_report_url(url: str) -> bool:
    """Check that a report_url looks like a real report path (not placeholder)."""
    if not url:
        return False
    if url in ("#", "/", ""):
        return False
    if "reports/" not in url:
        return False
    if url.endswith(".html") or "/reports/" in url:
        return True
    return False


def _guess_report_path_from_item(item: dict) -> Optional[Path]:
    """
    Attempt to resolve the on-disk HTML report for an item using its id + timestamp.
    Returns Path if file exists, else None.
    """
    item_id = item.get("id") or ""
    if not item_id:
        return None

    # Determine YYYY/MM from timestamp fields
    ts_str = (
        item.get("timestamp") or
        item.get("processed_at") or
        item.get("published_at") or
        ""
    )
    try:
        if ts_str:
            ts_str_clean = ts_str.replace("Z", "+00:00")
            dt = datetime.fromisoformat(ts_str_clean)
            yyyy = str(dt.year)
            mm   = f"{dt.month:02d}"
            candidate = REPORTS_ROOT / yyyy / mm / f"{item_id}.html"
            if candidate.exists() and candidate.stat().st_size > 512:
                return candidate
    except Exception:
        pass

    # Brute-force search across year/month subdirs (capped scan, performance-safe)
    if REPORTS_ROOT.exists():
        for year_dir in sorted(REPORTS_ROOT.iterdir(), reverse=True):
            if not year_dir.is_dir():
                continue
            for month_dir in sorted(year_dir.iterdir(), reverse=True):
                if not month_dir.is_dir():
                    continue
                candidate = month_dir / f"{item_id}.html"
                if candidate.exists() and candidate.stat().st_size > 512:
                    return candidate

    return None


def _build_report_url_from_path(path: Path) -> str:
    """Convert on-disk path to absolute public URL."""
    try:
        rel = path.relative_to(REPORTS_ROOT)
        return f"{BASE_URL.rstrip('/')}/reports/{rel.as_posix()}"
    except ValueError:
        return ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    t_start = time.monotonic()
    log.info("=" * 70)
    log.info("SYNC REPORT URLS  —  SENTINEL APEX v161.2 P0 Mandate")
    log.info("=" * 70)
    log.info("Manifest : %s", FEED_MANIFEST)
    log.info("API Feed : %s", API_FEED)
    log.info("Base URL : %s", BASE_URL)

    # ------------------------------------------------------------------
    # 1. Load api/feed.json (mandatory)
    # ------------------------------------------------------------------
    if not API_FEED.exists():
        log.error("api/feed.json not found — nothing to sync")
        return 1

    feed_data = _load_json_safe(API_FEED)
    if not isinstance(feed_data, list):
        log.error("api/feed.json is not a JSON array — cannot sync")
        return 1
    log.info("api/feed.json: %d items loaded", len(feed_data))

    # ------------------------------------------------------------------
    # 2. Build report_url map from feed_manifest.json
    # ------------------------------------------------------------------
    manifest_map: Dict[str, str] = {}  # id -> report_url

    if FEED_MANIFEST.exists():
        mdata = _load_json_safe(FEED_MANIFEST)
        if mdata is not None:
            # feed_manifest can be a list OR a dict with advisories/items key
            if isinstance(mdata, list):
                manifest_items = mdata
            elif isinstance(mdata, dict):
                manifest_items = (
                    mdata.get("advisories") or
                    mdata.get("items") or
                    mdata.get("entries") or
                    []
                )
            else:
                manifest_items = []

            for it in manifest_items:
                if not isinstance(it, dict):
                    continue
                iid  = it.get("id") or ""
                rurl = it.get("report_url") or it.get("internal_report_url") or ""
                if iid and rurl and _is_valid_report_url(rurl):
                    manifest_map[iid] = _make_absolute_url(rurl)

            log.info(
                "feed_manifest.json: %d items, %d have valid report_url",
                len(manifest_items), len(manifest_map)
            )
    else:
        log.warning("feed_manifest.json not found — will use disk fallback only")

    # ------------------------------------------------------------------
    # 3. Sync report_url into each api/feed.json item
    # ------------------------------------------------------------------
    synced_from_manifest = 0
    synced_from_disk     = 0
    already_valid        = 0
    not_found            = 0
    errors               = 0

    for item in feed_data:
        if not isinstance(item, dict):
            continue
        try:
            item_id = item.get("id") or ""
            existing = item.get("report_url") or ""

            # Already has a valid report_url — preserve it, don't overwrite
            if _is_valid_report_url(existing):
                # Ensure it's absolute
                abs_url = _make_absolute_url(existing)
                if abs_url != existing:
                    item["report_url"] = abs_url
                    item["internal_report_url"] = abs_url
                already_valid += 1
                continue

            # Try feed_manifest first (most reliable — written by generate_intel_reports.py)
            if item_id and item_id in manifest_map:
                rurl = manifest_map[item_id]
                item["report_url"]          = rurl
                item["internal_report_url"] = rurl
                if not item.get("validation_status") or item.get("validation_status") in ("", "pending"):
                    item["validation_status"] = "ok"
                synced_from_manifest += 1
                continue

            # Fallback: scan disk for the report file
            disk_path = _guess_report_path_from_item(item)
            if disk_path:
                rurl = _build_report_url_from_path(disk_path)
                if rurl:
                    item["report_url"]          = rurl
                    item["internal_report_url"] = rurl
                    if not item.get("validation_status") or item.get("validation_status") in ("", "pending"):
                        item["validation_status"] = "ok"
                    synced_from_disk += 1
                    continue

            # No report found for this item
            not_found += 1

        except Exception as e:
            log.warning("Error processing item %s: %s", item.get("id", "?"), e)
            errors += 1

    elapsed = time.monotonic() - t_start
    log.info(
        "SYNC COMPLETE: manifest=%d disk=%d already_valid=%d not_found=%d errors=%d "
        "total=%d elapsed=%.1fs",
        synced_from_manifest, synced_from_disk, already_valid,
        not_found, errors, len(feed_data), elapsed
    )

    # ------------------------------------------------------------------
    # 4. Atomic write api/feed.json
    # ------------------------------------------------------------------
    total_with_report = sum(
        1 for it in feed_data
        if isinstance(it, dict) and _is_valid_report_url(it.get("report_url") or "")
    )
    log.info(
        "api/feed.json post-sync: %d/%d items have report_url (%.0f%%)",
        total_with_report, len(feed_data),
        100 * total_with_report / max(len(feed_data), 1)
    )

    if not _atomic_write(API_FEED, feed_data):
        log.error("FATAL: failed to write api/feed.json — sync aborted")
        return 1
    log.info("api/feed.json written atomically")

    # ------------------------------------------------------------------
    # 5. Sync latest.json if present (keeps latest.json consistent)
    # ------------------------------------------------------------------
    if LATEST_JSON.exists():
        try:
            latest_data = _load_json_safe(LATEST_JSON)
            if isinstance(latest_data, list) and latest_data:
                # latest.json is typically a subset of feed — sync matching items
                feed_map = {it.get("id"): it for it in feed_data if isinstance(it, dict)}
                changed_latest = False
                for lat_item in latest_data:
                    if not isinstance(lat_item, dict):
                        continue
                    lid = lat_item.get("id")
                    if lid and lid in feed_map:
                        src_url = feed_map[lid].get("report_url") or ""
                        if _is_valid_report_url(src_url) and not _is_valid_report_url(lat_item.get("report_url") or ""):
                            lat_item["report_url"] = src_url
                            lat_item["internal_report_url"] = src_url
                            changed_latest = True
                if changed_latest:
                    _atomic_write(LATEST_JSON, latest_data)
                    log.info("api/latest.json updated with synced report_urls")
        except Exception as e:
            log.warning("latest.json sync non-fatal error: %s", e)

    log.info("DONE — report_url sync complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  