/**
 * MSSP tenant self-service (tenant_auth_version 2).
 *
 * Authority: the MSSP key's managed_tenants list stays the one tenant
 * authorization every consumer reads (handleMSSPFeed in
 * enterprise-endpoints.js, resolveTenant in cyber-watchdog.js). This module
 * lets the paying MSSP customer maintain that list themselves, without
 * ADMIN_SECRET:
 *
 *   - Owner is the authenticated subject (auth.sub), never a request field.
 *   - Tenant ids are generated by the server (tn_ + 80 random bits).
 *   - Membership is stored in one WatchdogLedger Durable Object instance per
 *     owner ("mssp:" + sub). That existing class already serializes
 *     requests per instance, so create/revoke are atomic without a KV
 *     read-modify-write.
 *   - For a v2 key, resolveAuth's managed_tenants is replaced by this list
 *     at request time (index.js resolveMsspMembership). The KV key record is
 *     deliberately NOT rewritten on every tenant change: a KV read can be
 *     stale for up to 60s, and writing back a stale record could undo a
 *     concurrent refund or suspension. The record keeps managed_tenants: []
 *     (fail closed if this store is unavailable) and tenant_auth_version: 2.
 *
 * Keys without tenant_auth_version 2 are unchanged: managed_tenants null
 * stays the documented legacy unrestricted mode, and an operator-set list
 * stays operator-managed (docs/MSSP_TENANT_IDENTITY_V185.md).
 *
 * Data semantics: a tenant scopes WHO may request tenant views. Every tenant
 * receives the same shared intelligence feed, filtered; there is no private
 * per-tenant intelligence store.
 */

export const TENANT_AUTH_VERSION = 2;
export const TENANT_MEMBERSHIP_STORAGE_KEY = "mssp_tenant_membership";
export const TENANT_DO_PREFIX = "mssp:";

export const TENANT_POLICY = Object.freeze({
  // Technical storage/abuse bound, the same 100 the Watchdog session claims
  // already cap managed_tenants at. It is not a commercial quota: the
  // commercial contract (config/commercial-contract.json) defines none.
  max_active_tenants: 100,
  // Revoked rows are kept for audit, oldest pruned beyond this.
  max_records: 500,
  name_max_length: 80,
});

const TENANT_ID_RE = /^tn_[0-9a-f]{20}$/;
// Printable text only: letters, marks, digits, spaces and plain punctuation.
// No control characters, no path or markup characters.
const TENANT_NAME_RE = /^[\p{L}\p{M}\p{N} .,&()'@+_-]+$/u;
const OWNER_FIELDS = ["mssp_email", "customer_id", "owner_id", "owner", "email", "sub", "tenant_id", "id", "mssp_id"];
const ALLOWED_CREATE_FIELDS = new Set(["name"]);

export const TENANT_DATA_SEMANTICS =
  "A tenant controls who may request tenant-scoped views. Every tenant is served the same shared "
  + "intelligence feed, filtered by the query; there is no private per-tenant intelligence store.";

export function isTenantId(x) {
  return typeof x === "string" && TENANT_ID_RE.test(x);
}

export function newTenantId(randomBytes) {
  const bytes = randomBytes(10);
  return "tn_" + Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function nameKey(name) {
  return name.normalize("NFKC").toLowerCase();
}

export function validateTenantName(raw) {
  if (typeof raw !== "string") return { error: "name_required" };
  // Control characters (newline, tab, NUL, C1) are rejected, not rewritten.
  if (/[\u0000-\u001f\u007f-\u009f\u2028\u2029]/.test(raw)) return { error: "name_invalid_characters" };
  const name = raw.normalize("NFKC").trim().replace(/ +/g, " ");
  if (!name) return { error: "name_required" };
  if (name.length > TENANT_POLICY.name_max_length) return { error: "name_too_long" };
  if (!TENANT_NAME_RE.test(name)) return { error: "name_invalid_characters" };
  return { name };
}

export function emptyMembership(owner) {
  return { version: 1, owner, tenants: [] };
}

export function activeTenantIds(state) {
  return (state?.tenants || []).filter((t) => t.status === "active").map((t) => t.id);
}

function publicTenant(t) {
  return { tenant_id: t.id, name: t.name, status: t.status, created_at: t.created_at, revoked_at: t.revoked_at || null };
}

/**
 * Pure decision for one membership operation. The Durable Object stores
 * `state` when the result is not readOnly and has no error.
 */
export function applyTenantMutation(current, op) {
  const owner = op && typeof op.owner === "string" ? op.owner : "";
  if (!owner) return { error: "owner_required", status: 400 };
  const state = current || emptyMembership(owner);
  // Defence in depth: the instance name already derives from the owner.
  if (state.owner !== owner) return { error: "not_found", status: 404 };

  if (op.type === "members") {
    return { readOnly: true, result: { initialized: !!current, tenant_ids: activeTenantIds(state) } };
  }
  if (op.type === "list") {
    return { readOnly: true, result: { tenants: state.tenants.map(publicTenant), active_count: activeTenantIds(state).length } };
  }
  if (op.type === "get") {
    const t = state.tenants.find((x) => x.id === op.id);
    return t ? { readOnly: true, result: { tenant: publicTenant(t) } } : { error: "not_found", status: 404 };
  }
  if (op.type === "check") {
    const t = state.tenants.find((x) => x.id === op.id);
    return { readOnly: true, result: { initialized: !!current, active: !!t && t.status === "active" } };
  }
  if (op.type === "create") {
    if (!isTenantId(op.id)) return { error: "invalid_tenant_id", status: 400 };
    const v = validateTenantName(op.name);
    if (v.error) return { error: v.error, status: 400 };
    if (state.tenants.some((t) => t.id === op.id)) return { error: "tenant_id_conflict", status: 409 };
    const active = state.tenants.filter((t) => t.status === "active");
    if (active.some((t) => nameKey(t.name) === nameKey(v.name))) return { error: "tenant_name_exists", status: 409 };
    if (active.length >= TENANT_POLICY.max_active_tenants) {
      return { error: "tenant_limit_reached", status: 409, limit: TENANT_POLICY.max_active_tenants };
    }
    const row = { id: op.id, name: v.name, status: "active", created_at: op.now, revoked_at: null };
    let tenants = [...state.tenants, row];
    if (tenants.length > TENANT_POLICY.max_records) {
      const revoked = tenants.filter((t) => t.status !== "active")
        .sort((a, b) => String(a.revoked_at).localeCompare(String(b.revoked_at)));
      const drop = new Set(revoked.slice(0, tenants.length - TENANT_POLICY.max_records).map((t) => t.id));
      tenants = tenants.filter((t) => !drop.has(t.id));
    }
    return { state: { ...state, tenants }, result: { tenant: publicTenant(row) } };
  }
  if (op.type === "revoke") {
    const i = state.tenants.findIndex((t) => t.id === op.id);
    if (i < 0) return { error: "not_found", status: 404 };
    const t = state.tenants[i];
    if (t.status !== "active") return { readOnly: true, result: { tenant: publicTenant(t) } };
    const tenants = state.tenants.slice();
    tenants[i] = { ...t, status: "revoked", revoked_at: op.now };
    return { state: { ...state, tenants }, result: { tenant: publicTenant(tenants[i]) } };
  }
  return { error: "invalid_op", status: 400 };
}

/** Storage adapter used by WatchdogLedger.fetch for a membership request. */
export async function runTenantMembershipOp(storage, op) {
  const current = (await storage.get(TENANT_MEMBERSHIP_STORAGE_KEY)) || null;
  const out = applyTenantMutation(current, op);
  if (!out.error && !out.readOnly) await storage.put(TENANT_MEMBERSHIP_STORAGE_KEY, out.state);
  const { state: _omit, ...rest } = out;
  return rest;
}

const NOT_FOUND = { status: 404, body: { error: "not_found", message: "Tenant not found." } };

function msspGuard(auth) {
  if (!auth || !auth.sub || auth.error) {
    return { status: 401, body: { error: "authentication_required", message: "Send your MSSP API key in X-API-Key." } };
  }
  if (auth.credential_type !== "api_key") {
    return { status: 403, body: { error: "api_key_required", message: "Tenant management requires your MSSP API key (X-API-Key)." } };
  }
  if (auth.tier !== "MSSP") {
    return { status: 403, body: { error: "forbidden", message: "Tenant management is included with the MSSP plan.", checkout: "/upgrade.html?plan=mssp" } };
  }
  if (auth.tenant_auth_version !== TENANT_AUTH_VERSION) {
    return {
      status: 409,
      body: {
        error: "tenant_self_service_unavailable_for_key",
        message: "This key's tenants are managed by the operator (legacy compatibility mode). Its current access is unchanged. Contact support to enable self-service tenant management.",
      },
    };
  }
  return null;
}

function failure(out) {
  if (out?.status === 404 || out?.error === "not_found") return NOT_FOUND;
  const body = { error: out?.error || "tenant_store_unavailable" };
  if (out?.limit != null) body.limit = out.limit;
  if (!out?.error || out.error === "tenant_store_unavailable") body.message = "Tenant store is temporarily unavailable. Nothing was changed.";
  return { status: out?.status || 503, body };
}

/**
 * GET    /api/mssp/tenants            list the caller's tenants
 * POST   /api/mssp/tenants            {"name": "..."} -> 201, server-generated tenant_id
 * GET    /api/mssp/tenants/{id}       one tenant
 * DELETE /api/mssp/tenants/{id}       revoke (feed and Watchdog access end at once)
 *
 * req: { path, method, auth, body, membership: { mutate(op) } | null, newId(), now }
 * Returns null for paths it does not own (/api/mssp/tenants/{id}/feed etc).
 */
export async function routeMsspTenants(req) {
  const path = req.path || "";
  const m = path.match(/^\/api\/mssp\/tenants(?:\/([^/]*))?$/);
  if (!m) return null;
  const id = m[1];
  const denied = msspGuard(req.auth);
  if (denied) return denied;
  const store = req.membership;
  const call = async (op) => {
    if (!store || typeof store.mutate !== "function") return { error: "tenant_store_unavailable", status: 503 };
    try {
      return await store.mutate({ ...op, owner: req.auth.sub, now: req.now });
    } catch {
      return { error: "tenant_store_unavailable", status: 503 };
    }
  };

  if (id === undefined) {
    if (req.method === "GET" || req.method === "HEAD") {
      const out = await call({ type: "list" });
      if (out.error) return failure(out);
      return {
        status: 200,
        body: {
          tenants: out.result.tenants,
          active_count: out.result.active_count,
          limits: { max_active_tenants: TENANT_POLICY.max_active_tenants },
          usage: {
            feed: "GET /api/mssp/tenants/{tenant_id}/feed",
            watchdog: "X-CDB-Watchdog-Tenant: {tenant_id} on /api/watchdog/*",
          },
          data_semantics: TENANT_DATA_SEMANTICS,
        },
      };
    }
    if (req.method === "POST") {
      const body = req.body;
      if (!body || typeof body !== "object" || Array.isArray(body)) {
        return { status: 400, body: { error: "invalid_body", message: 'Send a JSON object: {"name": "Customer name"}.' } };
      }
      const owned = OWNER_FIELDS.find((f) => Object.prototype.hasOwnProperty.call(body, f));
      if (owned) {
        return { status: 400, body: { error: "field_not_accepted", field: owned, message: "Tenant ownership comes from your API key and tenant ids are generated by the server." } };
      }
      const unknown = Object.keys(body).find((k) => !ALLOWED_CREATE_FIELDS.has(k));
      if (unknown) return { status: 400, body: { error: "field_not_accepted", field: unknown.slice(0, 40) } };
      const v = validateTenantName(body.name);
      if (v.error) return { status: 400, body: { error: v.error, max_length: TENANT_POLICY.name_max_length } };
      const out = await call({ type: "create", id: req.newId(), name: v.name });
      if (out.error) return failure(out);
      return { status: 201, body: { tenant: out.result.tenant, data_semantics: TENANT_DATA_SEMANTICS } };
    }
    return { status: 405, body: { error: "method_not_allowed" } };
  }

  // Unknown, malformed, other-owner and never-existed ids all look the same.
  if (!isTenantId(id)) return NOT_FOUND;
  if (req.method === "GET" || req.method === "HEAD") {
    const out = await call({ type: "get", id });
    if (out.error) return failure(out);
    return { status: 200, body: { tenant: out.result.tenant } };
  }
  if (req.method === "DELETE") {
    const out = await call({ type: "revoke", id });
    if (out.error) return failure(out);
    return { status: 200, body: { tenant: out.result.tenant, revoked: true } };
  }
  return { status: 405, body: { error: "method_not_allowed" } };
}

/**
 * True when this request selects an MSSP tenant, so a v2 key's membership
 * must be resolved before authorization (one Durable Object read). Untenanted
 * requests never pay for it.
 */
export function requestSelectsTenant(path, headers, searchParams, auth) {
  if (/^\/api\/mssp\/tenants\/[^/]+\/feed$/.test(path)) return true;
  if (!path.startsWith("/api/watchdog")) return false;
  const header = headers && typeof headers.get === "function" ? headers.get("X-CDB-Watchdog-Tenant") : null;
  return !!(header || searchParams?.get?.("tenant") || auth?.tenant);
}
