import os
import yaml
import uuid
import logging
from datetime import datetime
from agent.sovereignty_engine import sovereign_engine

logger = logging.getLogger("CDB-FACTORY")

class AssetFactory:
    """
    CYBERDUDEBIVASH® ASSET FACTORY (v2.0)
    Generates Signed, Sovereign Sigma and YARA rule packs.
    """
    def __init__(self, output_base="data/rule_packs"):
        self.output_base = output_base
        os.makedirs(self.output_base, exist_ok=True)
        self.legal_header = (
            "================================================================================\n"
            "PRODUCT:    CDB-SENTINEL-APEX-DETECTION-RULE\n"
            "OWNER:      CYBERDUDEBIVASH PVT LTD\n"
            "COPYRIGHT:  © 2026 CYBERDUDEBIVASH PVT LTD. ALL RIGHTS RESERVED.\n"
            "AUTHORITY:  GLOBAL CYBERSECURITY THREAT INTELLIGENCE SOVEREIGNTY\n"
            "================================================================================\n"
        )

    def generate_sigma_rule(self, intel_data):
        """Creates a signed Sigma rule with CDB Signature metadata."""
        rule_id = str(uuid.uuid4())
        # Base logic for Sigma
        sigma_template = {
            'title': f"CDB-Detection: {intel_data['title']}",
            'id': rule_id,
            'status': 'stable',
            'description': f"Automated detection for {intel_data['title']}. Generated by Sentinel APEX.",
            'author': 'CYBERDUDEBIVASH PVT LTD',
            'date': datetime.now().strftime("%Y/%m/%d"),
            'logsource': {'category': 'process_creation', 'product': 'windows'},
            'detection': {
                'selection': {'Image|endswith': intel_data.get('malicious_process', 'cmd.exe')},
                'condition': 'selection'
            },
            'level': 'high'
        }
        
        # Serialize and Sign
        raw_content = yaml.dump(sigma_template, default_flow_style=False)
        signature = sovereign_engine.sign_asset(raw_content)
        
        # Add Header and Signature to the final file
        final_rule = f"{self.legal_header}signature: {signature}\n{raw_content}"
        
        file_path = os.path.join(self.output_base, f"sigma_{rule_id[:8]}.yml")
        with open(file_path, 'w') as f:
            f.write(final_rule)
        return file_path

    def generate_yara_rule(self, intel_data):
        """Creates a signed, professional YARA rule."""
        rule_name = f"CDB_Scanner_{int(datetime.now().timestamp())}"
        ioc_string = intel_data.get('main_ioc', 'malicious_pattern')
        
        # Prepare content for signing
        rule_body = f"rule {rule_name} {{\n    meta:\n        author = \"CYBERDUDEBIVASH PVT LTD\"\n    strings:\n        $s1 = \"{ioc_string}\"\n    condition:\n        any of them\n}}"
        signature = sovereign_engine.sign_asset(rule_body)
        
        # Inject Sovereign Metadata
        final_yara = f"/*\n{self.legal_header}SIGNATURE: {signature}\n*/\n\n{rule_body}"
        
        file_path = os.path.join(self.output_base, f"yara_{rule_name}.yar")
        with open(file_path, 'w') as f:
            f.write(final_yara)
        return file_path

asset_engine = AssetFactory()
