variable "cluster_name" { type = string; default = "" }
variable "cluster_version" { type = string; default = "1.30" }
variable "vpc_id" { type = string; default = "" }
variable "subnet_ids" { type = list(string); default = [] }
variable "cluster_endpoint_private_access" { type = bool; default = true }
variable "cluster_endpoint_public_access" { type = bool; default = true }
variable "cluster_endpoint_public_access_cidrs" { type = list(string); default = [] }
variable "node_groups" { type = any; default = {} }
variable "cluster_addons" { type = any; default = {} }
variable "enable_irsa" { type = bool; default = true }
variable "tags" { type = map(string); default = {} }
