"""
blog_post_generator.py — CyberDudeBivash v4.5 APEX
Final Production Version: AI Triage & Forensic Indicator Tables.
"""
from typing import List, Dict, Optional
from datetime import datetime, timezone

def generate_headline(intel_items: List[Dict]) -> str:
    """
    Generates a high-impact, consolidated headline for the report.
    Picks the primary threat and notes the volume of secondary updates.
    """
    if not intel_items:
        return "CDB Sentinel: Global Intelligence Sweep"
    
    primary = intel_items[0].get('title', 'Unknown Threat')
    if len(intel_items) > 1:
        return f"CRITICAL: {primary} (+{len(intel_items)-1} Intelligence Nodes)"
    return f"THREAT ADVISORY: {primary}"

def generate_full_post_content(intel_items: List[Dict], iocs: Optional[Dict] = None) -> str:
    """
    Assembles the professional HTML body for the Blogger publication.
    Includes forensic IoC tables and dynamic timestamping.
    """
    # Initialize HTML sequence with a professional cyber-intel header
    html = [f"""
    <div style="font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1a1f36; line-height: 1.8; max-width: 800px; margin: auto; border: 1px solid #e3e8ee; border-radius: 8px; overflow: hidden;">
        <div style="background: #1a1f36; color: #ffffff; padding: 30px; text-align: left;">
            <h1 style="margin: 0; font-size: 26px; letter-spacing: 1px;">CYBERDUDEBIVASH THREAT REPORT</h1>
            <p style="margin: 8px 0 0; opacity: 0.8; font-family: monospace;">
                STATUS: ACTIVE TRIAGE | GENERATED: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC
            </p>
        </div>
        <div style="padding: 25px;">
    """]

    # 1. Intelligence Node Summaries
    html.append('<h2 style="color: #5469d4; border-bottom: 2px solid #f7fafc; padding-bottom: 10px;">Executive Summary</h2>')
    for item in intel_items:
        html.append(f"""
        <div style="margin-bottom: 25px; padding: 15px; background: #f7fafc; border-left: 4px solid #5469d4; border-radius: 4px;">
            <h3 style="margin: 0 0 10px 0; font-size: 18px;">
                <a href="{item.get('link', '#')}" style="color: #1a73e8; text-decoration: none;">{item.get('title', 'Untitled')}</a>
            </h3>
            <p style="margin: 0; font-size: 15px; color: #4f566b;">{item.get('summary', 'No summary available.')}</p>
        </div>
        """)

    # 2. Forensic Indicators (IoCs) Section
    # Renders extracted technical data into a scannable table
    if iocs and any(iocs.values()):
        html.append("""
        <h2 style="color: #cf1124; margin-top: 40px; border-bottom: 2px solid #f7fafc; padding-bottom: 10px;">Technical Indicators (IoCs)</h2>
        <div style="overflow-x: auto;">
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 14px; background: #ffffff;">
                <thead>
                    <tr style="background: #f7fafc; border-bottom: 2px solid #e3e8ee; text-align: left;">
                        <th style="padding: 12px; color: #4f566b;">Type</th>
                        <th style="padding: 12px; color: #4f566b;">Forensic Value</th>
                    </tr>
                </thead>
                <tbody>""")
        
        for ioc_type, values in iocs.items():
            for val in values:
                html.append(f"""
                <tr style="border-bottom: 1px solid #e3e8ee;">
                    <td style="padding: 12px; font-weight: bold; color: #1a1f36; white-space: nowrap;">{ioc_type.upper()}</td>
                    <td style="padding: 12px; font-family: 'Courier New', monospace; color: #cf1124; word-break: break-all;">{val}</td>
                </tr>""")
        html.append("</tbody></table></div>")
    else:
        html.append("""
        <div style="padding: 20px; background: #fff4f4; border-radius: 4px; color: #cf1124; margin-top: 30px;">
            <strong>Notice:</strong> No specific technical indicators were extracted in this sweep.
        </div>
        """)

    # 3. Footer and Legal
    html.append(f"""
        </div>
        <div style="background: #f7fafc; padding: 20px; text-align: center; border-top: 1px solid #e3e8ee;">
            <p style="margin: 0; font-size: 13px; color: #a3acb9;">
                © {datetime.now().year} CyberDudeBivash Pvt Ltd — Automated Threat Intelligence Platform
            </p>
            <p style="margin: 5px 0 0; font-size: 11px; color: #c1c9d2;">
                This report was autonomously generated by the Sentinel APEX Engine.
            </p>
        </div>
    </div>
    """)

    return "".join(html)

def _calculate_cdb_score(title: str, corpus: str) -> float:
    """
    Internal risk matrix to determine report priority.
    """
    score = 5.0
    # Weighted keywords for severity assessment
    matrix = {
        "ransomware": 2.5,
        "zero-day": 3.0,
        "critical": 1.5,
        "exploit": 1.0,
        "cve-2026": 2.0,
        "vulnerability": 0.5
    }
    
    text = f"{title} {corpus}".lower()
    for keyword, weight in matrix.items():
        if keyword in text:
            score += weight
            
    return min(10.0, score)
