#!/usr/bin/env python3
"""
premium_report_generator.py — CyberDudeBivash v16.4
The "Intelligence Architect": Generates 18-section premium reports.
"""

import logging
from typing import Dict
from agent.enricher import enricher
from agent.risk_engine import risk_engine

logger = logging.getLogger("CDB-GENERATOR")

class PremiumReportGenerator:
    def __init__(self):
        self.target_word_count = 2500

    def prepare_report(self, entry: Dict) -> Dict:
        """
        Synthesizes raw feed data into an enriched intelligence object.
        [Strictly matches the Orchestrator's call]
        """
        logger.info(f"🏗️ ARCHITECT: Preparing high-fidelity data for: {entry['title'][:50]}")
        
        # Core Enrichment
        enriched_content = enricher.enrich(entry['link'])
        score_data = risk_engine.analyze(enriched_content)

        return {
            "headline": entry['title'],
            "link": entry['link'],
            "content_raw": enriched_content,
            "technical_dive": enriched_content[:1500], # Simulated section
            "risk_score": score_data.get('score', 5.0),
            "severity": score_data.get('severity', 'MEDIUM'),
            "mitre_attacks": score_data.get('mitre', []),
            "iocs": score_data.get('iocs', [])
        }

    def generate_html(self, data: Dict) -> str:
        """
        Renders the 18-section HTML report.
        """
        # Logic for premium HTML formatting
        signature_block = f"<br><hr><p><b>Sovereign Signature:</b> {data.get('signature', 'UNSIGNED')}</p>"
        
        html_template = f"""
        <div style="font-family: Arial; line-height: 1.6;">
            <h1>🚨 {data['headline']}</h1>
            <h3>Risk Score: {data['risk_score']}/10 | Severity: {data['severity']}</h3>
            <p>{data['technical_dive']}</p>
            {signature_block}
            <p style="color: grey; font-size: 0.8em;">Generated by CDB Sentinel APEX v16.4</p>
        </div>
        """
        return html_template

# Global instance for the Orchestrator
premium_report_gen = PremiumReportGenerator()
