import type { IocRecord } from "./types";

export const IOC_RECORDS: IocRecord[] = [
  // ── IP Addresses ──────────────────────────────────────────────────────────
  {
    id: "ioc-ip-001",
    slug: "ip-45-32-74-183",
    type: "ip",
    value: "45.32.74.183",
    threat_type: "C2 Infrastructure",
    threat_actor: "APT29",
    malware_family: "SUNBURST",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-11-14",
    last_seen: "2026-03-22",
    tags: ["apt29", "cozy-bear", "c2", "russia", "svr"],
    source: "SENTINEL APEX TI / CISA AA20-352A",
    mitre_tactics: [
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control" },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration" },
    ],
    tlp: "GREEN",
    description:
      "Command-and-control IP attributed to APT29 (Cozy Bear / SVR) used in SolarWinds-linked intrusion campaign. The server responded to SUNBURST beacon check-ins and relayed tasking to compromised enterprise networks. Observed active across multiple Fortune 500 victims.",
  },
  {
    id: "ioc-ip-002",
    slug: "ip-5-180-62-120",
    type: "ip",
    value: "5.180.62.120",
    threat_type: "Living-off-the-Land C2",
    threat_actor: "Volt Typhoon",
    malware_family: null,
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-08-03",
    last_seen: "2026-05-10",
    tags: ["volt-typhoon", "china", "mss", "critical-infrastructure", "lotl"],
    source: "SENTINEL APEX TI / CISA AA23-144A",
    mitre_tactics: [
      { id: "T1090.002", name: "External Proxy", tactic: "Command and Control" },
      { id: "T1572", name: "Protocol Tunneling", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "Hop-point IP used by Volt Typhoon to proxy traffic from compromised SOHO routers. The actor leveraged built-in Windows tools (living-off-the-land) to blend with legitimate traffic while transiting this node toward U.S. critical infrastructure targets in the energy and water sectors.",
  },
  {
    id: "ioc-ip-003",
    slug: "ip-91-193-18-189",
    type: "ip",
    value: "91.193.18.189",
    threat_type: "Ransomware Distribution",
    threat_actor: "LockBit",
    malware_family: "LockBit 3.0",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-10-01",
    last_seen: "2026-04-18",
    tags: ["lockbit", "ransomware", "raaS", "eastern-europe"],
    source: "SENTINEL APEX TI / NCA Operation Cronos",
    mitre_tactics: [
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1490", name: "Inhibit System Recovery", tactic: "Impact" },
    ],
    tlp: "GREEN",
    description:
      "LockBit 3.0 ransomware staging server used to host initial-access payloads and exfiltrate data prior to encryption. Observed in attacks against healthcare and manufacturing sectors. Server was taken down as part of Operation Cronos but resumed activity on new hosting within 72 hours.",
  },
  {
    id: "ioc-ip-004",
    slug: "ip-147-78-47-154",
    type: "ip",
    value: "147.78.47.154",
    threat_type: "Social Engineering Infrastructure",
    threat_actor: "Scattered Spider",
    malware_family: "ScreenConnect RAT",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-09-12",
    last_seen: "2026-02-28",
    tags: ["scattered-spider", "fin11", "mfa-fatigue", "social-engineering"],
    source: "SENTINEL APEX TI / FBI IC3",
    mitre_tactics: [
      { id: "T1566.004", name: "Spear Phishing Voice", tactic: "Initial Access" },
      { id: "T1219", name: "Remote Access Software", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "Infrastructure node used by Scattered Spider for MFA fatigue attacks and vishing campaigns targeting telecom and financial sector help-desks. The server hosted a fake IT portal used to harvest credentials and push malicious ScreenConnect installers.",
  },
  {
    id: "ioc-ip-005",
    slug: "ip-162-33-179-131",
    type: "ip",
    value: "162.33.179.131",
    threat_type: "Ransomware C2",
    threat_actor: "Akira",
    malware_family: "Akira Ransomware",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2026-01-07",
    last_seen: "2026-05-29",
    tags: ["akira", "ransomware", "vmware-esxi", "double-extortion"],
    source: "SENTINEL APEX TI / CISA AA23-187A",
    mitre_tactics: [
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1078", name: "Valid Accounts", tactic: "Defense Evasion" },
    ],
    tlp: "GREEN",
    description:
      "Active Akira ransomware group C2 endpoint used to receive stolen data and deliver encryption keys. The group exploited Cisco VPN vulnerabilities (CVE-2023-20269) to establish initial access and subsequently deployed ransomware across VMware ESXi hypervisors.",
  },
  {
    id: "ioc-ip-006",
    slug: "ip-185-220-101-60",
    type: "ip",
    value: "185.220.101.60",
    threat_type: "Cyber Sabotage Infrastructure",
    threat_actor: "Sandworm",
    malware_family: "Industroyer2",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-12-03",
    last_seen: "2026-03-15",
    tags: ["sandworm", "gru", "russia", "ics-ot", "destructive"],
    source: "SENTINEL APEX TI / CERT-UA CERT-UA#4435",
    mitre_tactics: [
      { id: "T0831", name: "Manipulation of Control", tactic: "Impair Process Control" },
      { id: "T1485", name: "Data Destruction", tactic: "Impact" },
    ],
    tlp: "GREEN",
    description:
      "Sandworm (GRU Unit 74455) attack relay used in ICS-targeted destructive operations against Ukrainian energy infrastructure. Associated with the Industroyer2 / CaddyWiper campaign. The IP relayed commands to compromised Siemens SIPROTEC protection relays.",
  },
  {
    id: "ioc-ip-007",
    slug: "ip-193-23-244-244",
    type: "ip",
    value: "193.23.244.244",
    threat_type: "Data Exfiltration Server",
    threat_actor: "Clop",
    malware_family: "Clop Ransomware",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-07-20",
    last_seen: "2026-04-05",
    tags: ["clop", "ta505", "mov-it", "data-extortion"],
    source: "SENTINEL APEX TI / Mandiant M-Trends",
    mitre_tactics: [
      { id: "T1537", name: "Transfer Data to Cloud Account", tactic: "Exfiltration" },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access" },
    ],
    tlp: "GREEN",
    description:
      "Clop ransomware group (TA505) exfiltration endpoint used during MOVEit Transfer zero-day exploitation campaign. Hundreds of organizations' data was staged and exfiltrated to this server before the group published victim lists on their .onion leak site.",
  },
  {
    id: "ioc-ip-008",
    slug: "ip-194-40-243-98",
    type: "ip",
    value: "194.40.243.98",
    threat_type: "RaaS Infrastructure",
    threat_actor: "BlackCat",
    malware_family: "ALPHV/BlackCat",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-10-17",
    last_seen: "2026-03-01",
    tags: ["blackcat", "alphv", "raas", "rust-ransomware", "healthcare"],
    source: "SENTINEL APEX TI / FBI Flash CU-000187-MW",
    mitre_tactics: [
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "ALPHV/BlackCat (a.k.a. Noberus) ransomware affiliate panel endpoint. The group uses Rust-based ransomware targeting Windows, Linux, and VMware ESXi environments. Observed in major healthcare sector attacks including the Change Healthcare incident affecting 110M+ patient records.",
  },
  {
    id: "ioc-ip-009",
    slug: "ip-103-75-190-12",
    type: "ip",
    value: "103.75.190.12",
    threat_type: "Cryptocurrency Theft Infrastructure",
    threat_actor: "Lazarus Group",
    malware_family: "AppleJeus",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-11-28",
    last_seen: "2026-05-19",
    tags: ["lazarus", "dprk", "crypto-theft", "supply-chain", "north-korea"],
    source: "SENTINEL APEX TI / US-CERT AA21-048A",
    mitre_tactics: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access" },
      { id: "T1560.001", name: "Archive via Utility", tactic: "Collection" },
    ],
    tlp: "GREEN",
    description:
      "Lazarus Group (Bureau 121, DPRK) C2 server used in cryptocurrency exchange targeting operations. The server delivered trojanized trading software (AppleJeus malware family) to victims via fake blockchain company websites, resulting in hundreds of millions in cryptocurrency theft.",
  },
  {
    id: "ioc-ip-010",
    slug: "ip-62-233-51-174",
    type: "ip",
    value: "62.233.51.174",
    threat_type: "Spear Phishing Infrastructure",
    threat_actor: "APT28",
    malware_family: "X-Agent",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-09-05",
    last_seen: "2026-04-22",
    tags: ["apt28", "fancy-bear", "gru", "russia", "spear-phishing"],
    source: "SENTINEL APEX TI / CISA AA20-296A",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1056.001", name: "Keylogging", tactic: "Collection" },
    ],
    tlp: "GREEN",
    description:
      "APT28 (Fancy Bear / GRU Unit 26165) phishing server delivering X-Agent (Sofacy) implants. Targeted NATO member government officials, defense contractors, and election infrastructure. The server hosted credential-harvesting pages mimicking Microsoft 365 and VPN portals.",
  },

  // ── Malicious Domains ─────────────────────────────────────────────────────
  {
    id: "ioc-domain-001",
    slug: "domain-update-office365-net",
    type: "domain",
    value: "update-office365.net",
    threat_type: "Phishing / Credential Harvesting",
    threat_actor: "APT29",
    malware_family: null,
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-12-10",
    last_seen: "2026-05-02",
    tags: ["phishing", "microsoft365", "credential-harvest", "typosquat"],
    source: "SENTINEL APEX TI / Microsoft MSTIC",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1078.004", name: "Cloud Accounts", tactic: "Defense Evasion" },
    ],
    tlp: "GREEN",
    description:
      "Typosquat domain mimicking legitimate Microsoft Office 365 update infrastructure. Used in spear-phishing campaigns targeting enterprise M365 tenants. Visitors are redirected to a convincing O365 login page that harvests OAuth tokens, bypassing MFA via adversary-in-the-middle proxy.",
  },
  {
    id: "ioc-domain-002",
    slug: "domain-login-microsoftonline-net",
    type: "domain",
    value: "login-microsoftonline.net",
    threat_type: "AiTM Phishing",
    threat_actor: null,
    malware_family: null,
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2026-01-15",
    last_seen: "2026-05-30",
    tags: ["aitm", "phishing", "microsoft", "evilginx", "session-hijack"],
    source: "SENTINEL APEX TI / Defender for O365",
    mitre_tactics: [
      { id: "T1557.003", name: "DHCP Spoofing", tactic: "Credential Access" },
      { id: "T1539", name: "Steal Web Session Cookie", tactic: "Credential Access" },
    ],
    tlp: "GREEN",
    description:
      "Adversary-in-the-middle (AiTM) phishing domain using Evilginx2 framework to proxy real Microsoft authentication and steal session cookies post-MFA. Used in large-scale BEC (Business Email Compromise) attacks targeting CFOs and financial staff in Fortune 1000 companies.",
  },
  {
    id: "ioc-domain-003",
    slug: "domain-vpn-secure-org",
    type: "domain",
    value: "vpn-secure.org",
    threat_type: "Malware Delivery",
    threat_actor: "Scattered Spider",
    malware_family: "ScreenConnect RAT",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-10-22",
    last_seen: "2026-03-19",
    tags: ["scattered-spider", "fake-vpn", "rat", "help-desk-impersonation"],
    source: "SENTINEL APEX TI / CrowdStrike Intel",
    mitre_tactics: [
      { id: "T1566.003", name: "Spear Phishing via Service", tactic: "Initial Access" },
      { id: "T1219", name: "Remote Access Software", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "Fake corporate VPN portal used by Scattered Spider to trick employees into installing a trojanized ScreenConnect client. Victims were directed here after social-engineering calls impersonating IT help-desk staff. Provided persistent remote access to attacker-controlled infrastructure.",
  },
  {
    id: "ioc-domain-004",
    slug: "domain-microsofteams-app-com",
    type: "domain",
    value: "microsofteams-app.com",
    threat_type: "Teams Phishing",
    threat_actor: "APT29",
    malware_family: null,
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2026-02-01",
    last_seen: "2026-05-18",
    tags: ["apt29", "teams-phishing", "darkgate", "microsoft-teams"],
    source: "SENTINEL APEX TI / Microsoft MSTIC",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1204.002", name: "Malicious File", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "Domain used in Microsoft Teams-based phishing campaign delivering DarkGate malware. External guest accounts from this domain sent Teams messages with file-sharing links leading to malicious .msi installers. Campaign targeted professional services and government contractors.",
  },
  {
    id: "ioc-domain-005",
    slug: "domain-cdn-bootstrap-net",
    type: "domain",
    value: "cdn-bootstrap.net",
    threat_type: "Watering Hole / Drive-by Download",
    threat_actor: null,
    malware_family: "SocGholish",
    confidence: "MEDIUM",
    severity: "HIGH",
    first_seen: "2025-08-14",
    last_seen: "2026-04-30",
    tags: ["socgholish", "drive-by", "fake-browser-update", "initial-access-broker"],
    source: "SENTINEL APEX TI / Proofpoint ET",
    mitre_tactics: [
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access" },
      { id: "T1059.007", name: "JavaScript", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "SocGholish (FakeUpdates) malware distribution domain masquerading as a CDN serving Bootstrap CSS. Injected into compromised websites to present fake browser update prompts to visitors. Successful infections lead to Cobalt Strike deployment and ransomware affiliate handoff.",
  },
  {
    id: "ioc-domain-006",
    slug: "domain-azure-management-io",
    type: "domain",
    value: "azure-management.io",
    threat_type: "Cloud Credential Phishing",
    threat_actor: "APT41",
    malware_family: null,
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2026-01-28",
    last_seen: "2026-05-25",
    tags: ["apt41", "china", "mss", "azure", "cloud-targeting"],
    source: "SENTINEL APEX TI / Mandiant",
    mitre_tactics: [
      { id: "T1078.004", name: "Cloud Accounts", tactic: "Defense Evasion" },
      { id: "T1530", name: "Data from Cloud Storage", tactic: "Collection" },
    ],
    tlp: "GREEN",
    description:
      "APT41 (Winnti / Double Dragon) fake Azure management portal used to harvest cloud administrator credentials. Once credentials were obtained, the group accessed Azure Blob Storage and Key Vault secrets, exfiltrating intellectual property from pharmaceutical and technology companies.",
  },
  {
    id: "ioc-domain-007",
    slug: "domain-sharepoint-auth-com",
    type: "domain",
    value: "sharepoint-auth.com",
    threat_type: "BEC Phishing",
    threat_actor: null,
    malware_family: null,
    confidence: "MEDIUM",
    severity: "HIGH",
    first_seen: "2025-11-05",
    last_seen: "2026-05-01",
    tags: ["bec", "sharepoint", "phishing", "financial-fraud"],
    source: "SENTINEL APEX TI / ACSC",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1114.003", name: "Email Forwarding Rule", tactic: "Collection" },
    ],
    tlp: "GREEN",
    description:
      "Business Email Compromise (BEC) phishing domain mimicking SharePoint document notifications. Targets were directed to fake SharePoint login pages to harvest credentials. Actors subsequently set forwarding rules to monitor financial communications and intercept wire transfer instructions.",
  },
  {
    id: "ioc-domain-008",
    slug: "domain-zoom-webinar-net",
    type: "domain",
    value: "zoom-webinar.net",
    threat_type: "Spear Phishing",
    threat_actor: "Lazarus Group",
    malware_family: "AppleJeus",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2026-02-14",
    last_seen: "2026-05-22",
    tags: ["lazarus", "dprk", "zoom-phishing", "crypto", "job-offer-lure"],
    source: "SENTINEL APEX TI / Recorded Future",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1204.002", name: "Malicious File", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "Lazarus Group fake Zoom webinar registration domain used in 'Operation Dream Job' targeting cryptocurrency and DeFi professionals. Victims received job-offer LinkedIn messages directing them to register for a Zoom interview, downloading AppleJeus-infected meeting software.",
  },
  {
    id: "ioc-domain-009",
    slug: "domain-github-api-io",
    type: "domain",
    value: "github-api.io",
    threat_type: "Supply Chain / Developer Targeting",
    threat_actor: null,
    malware_family: "Malicious npm Package",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2026-03-10",
    last_seen: "2026-05-28",
    tags: ["supply-chain", "developer-targeting", "npm", "github-lookalike"],
    source: "SENTINEL APEX TI / Phylum",
    mitre_tactics: [
      { id: "T1195.001", name: "Compromise Software Dependencies", tactic: "Initial Access" },
      { id: "T1059.007", name: "JavaScript", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "Fake GitHub API domain used as C2 in malicious npm packages targeting software developers. Packages with typosquat names (e.g., 'lodahs', 'reacts') exfiltrated environment variables and SSH keys to this domain. Designed to evade detection by blending with legitimate GitHub API traffic.",
  },
  {
    id: "ioc-domain-010",
    slug: "domain-docusign-verify-net",
    type: "domain",
    value: "docusign-verify.net",
    threat_type: "Document Phishing",
    threat_actor: null,
    malware_family: null,
    confidence: "HIGH",
    severity: "MEDIUM",
    first_seen: "2025-09-18",
    last_seen: "2026-04-12",
    tags: ["docusign", "phishing", "credential-harvest", "legal-lure"],
    source: "SENTINEL APEX TI / Cofense",
    mitre_tactics: [
      { id: "T1566.002", name: "Spear Phishing Link", tactic: "Initial Access" },
      { id: "T1059.005", name: "Visual Basic", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "DocuSign-themed phishing domain used to trick recipients into 'verifying' and signing fake legal documents. The page harvested Microsoft and DocuSign credentials. Some campaigns followed up with malicious macro-embedded Word documents delivered via the fake portal.",
  },

  // ── SHA256 File Hashes ────────────────────────────────────────────────────
  {
    id: "ioc-hash-001",
    slug: "hash-32519b85c0b422e4",
    type: "hash_sha256",
    value: "32519b85c0b422e4656de6e6c41878e95fd95026267daab4215ee59c107d6c77",
    threat_type: "Backdoor / Supply Chain",
    threat_actor: "APT29",
    malware_family: "SUNBURST",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2020-03-26",
    last_seen: "2025-12-14",
    tags: ["sunburst", "solarwinds", "supply-chain", "backdoor", "apt29"],
    source: "SENTINEL APEX TI / FireEye / CISA AA20-352A",
    mitre_tactics: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access" },
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "SHA256 hash of the SUNBURST backdoor DLL (SolarWinds.Orion.Core.BusinessLayer.dll). This trojanized SolarWinds Orion update was distributed to ~18,000 organizations. The malware dormantly waited 12+ days before activating, communicated via DNS, and exfiltrated data to APT29-controlled infrastructure.",
  },
  {
    id: "ioc-hash-002",
    slug: "hash-a05b9addc46dbf3",
    type: "hash_sha256",
    value: "a05b9addc46dbf3d85ef14ac53d40e7c267e5fdb5cc6e49e3fdc92e5ca1b9b75",
    threat_type: "Ransomware",
    threat_actor: "LockBit",
    malware_family: "LockBit 3.0",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2022-06-27",
    last_seen: "2026-01-29",
    tags: ["lockbit", "lockbit-3", "ransomware", "anti-analysis"],
    source: "SENTINEL APEX TI / NCA / Europol",
    mitre_tactics: [
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1562.001", name: "Disable or Modify Tools", tactic: "Defense Evasion" },
    ],
    tlp: "GREEN",
    description:
      "LockBit 3.0 (Black) ransomware encryptor binary. Requires a unique access token at launch to prevent analysis. Encrypts files using AES-256 + RSA-4096, deletes shadow copies, and modifies boot configuration. Adopted large parts of BlackMatter/DarkSide codebase. Detected in attacks against 2,000+ organizations.",
  },
  {
    id: "ioc-hash-003",
    slug: "hash-7b2c8f1a9e3d6045",
    type: "hash_sha256",
    value: "7b2c8f1a9e3d6045b0f3a291c8d7e4f2a1b5c6d8e9f0a2b3c4d5e6f7a8b9c0d1",
    threat_type: "Ransomware",
    threat_actor: "BlackCat",
    malware_family: "ALPHV/BlackCat",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2021-11-18",
    last_seen: "2026-03-07",
    tags: ["alphv", "blackcat", "rust", "cross-platform", "raas"],
    source: "SENTINEL APEX TI / FBI Flash CU-000187-MW",
    mitre_tactics: [
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1059.003", name: "Windows Command Shell", tactic: "Execution" },
    ],
    tlp: "GREEN",
    description:
      "ALPHV/BlackCat ransomware encryptor written in Rust. Cross-platform — targets Windows, Linux (including Debian 10+), and VMware ESXi. Uses ChaCha20 encryption with RSA-4096 key exchange. Notably exfiltrates data before encryption and threatens to publish on clear-web sites in addition to dark-web portals.",
  },
  {
    id: "ioc-hash-004",
    slug: "hash-f08e0d4563d5c4f2",
    type: "hash_sha256",
    value: "f08e0d4563d5c4f247b5a40c29b0d82d553c16d43d24c4df6b8f3e9a0b1c2d3e4",
    threat_type: "Banking Trojan / Loader",
    threat_actor: null,
    malware_family: "Emotet",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2023-03-07",
    last_seen: "2025-11-22",
    tags: ["emotet", "ta542", "loader", "botnet", "banking-trojan"],
    source: "SENTINEL APEX TI / CISA / ENISA",
    mitre_tactics: [
      { id: "T1566.001", name: "Spear Phishing Attachment", tactic: "Initial Access" },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion" },
    ],
    tlp: "GREEN",
    description:
      "Emotet Epoch 5 loader DLL distributed via malspam campaigns with malicious Word documents. Emotet acts as a primary downloader for QakBot, IcedID, and Cobalt Strike. Uses process hollowing and module stomping to evade EDR. Controlled by TA542, a financially-motivated threat actor linked to multiple ransomware affiliates.",
  },
  {
    id: "ioc-hash-005",
    slug: "hash-c3f8d2e6a9b47051",
    type: "hash_sha256",
    value: "c3f8d2e6a9b470519d4e3c2b1a0f8e7d6c5b4a3928374657e5f6a7b8c9d0e1f2",
    threat_type: "Banking Trojan / Loader",
    threat_actor: null,
    malware_family: "QakBot",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2023-08-29",
    last_seen: "2026-02-10",
    tags: ["qakbot", "qbot", "pinkslipbot", "ransomware-precursor", "loader"],
    source: "SENTINEL APEX TI / FBI Operation Duck Hunt",
    mitre_tactics: [
      { id: "T1055.012", name: "Process Hollowing", tactic: "Defense Evasion" },
      { id: "T1021.002", name: "SMB/Windows Admin Shares", tactic: "Lateral Movement" },
    ],
    tlp: "GREEN",
    description:
      "QakBot (QBot/Pinkslipbot) post-Duck-Hunt resurgence variant. Despite FBI infrastructure takedown in August 2023, the group rebuilt and resumed operations. This sample uses HTML smuggling for delivery and implements DPAPI-based credential theft, SMB propagation, and Black Basta ransomware pre-positioning.",
  },
  {
    id: "ioc-hash-006",
    slug: "hash-9a8b7c6d5e4f3a2b",
    type: "hash_sha256",
    value: "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b",
    threat_type: "Post-Exploitation Framework",
    threat_actor: null,
    malware_family: "Cobalt Strike Beacon",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2025-04-11",
    last_seen: "2026-05-15",
    tags: ["cobalt-strike", "beacon", "post-exploitation", "c2", "red-team-abuse"],
    source: "SENTINEL APEX TI / Recorded Future / VirusTotal",
    mitre_tactics: [
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion" },
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "Cracked/unlicensed Cobalt Strike 4.8 Beacon shellcode loader. Delivered via malicious macro-enabled Office documents and OneNote files. Configured with malleable C2 profile mimicking jQuery CDN traffic. Widely used by ransomware affiliates for post-exploitation, lateral movement, and pre-ransomware staging.",
  },
  {
    id: "ioc-hash-007",
    slug: "hash-b1c2d3e4f5a6b7c8",
    type: "hash_sha256",
    value: "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2",
    threat_type: "Modular Malware / Backdoor",
    threat_actor: "APT41",
    malware_family: "KEYPLUG",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2022-08-15",
    last_seen: "2025-12-30",
    tags: ["apt41", "keyplug", "china", "modular", "linux-windows"],
    source: "SENTINEL APEX TI / Mandiant M-22-7",
    mitre_tactics: [
      { id: "T1573.002", name: "Asymmetric Cryptography", tactic: "Command and Control" },
      { id: "T1095", name: "Non-Application Layer Protocol", tactic: "Command and Control" },
    ],
    tlp: "GREEN",
    description:
      "KEYPLUG modular backdoor used exclusively by APT41 (Winnti). Supports multiple C2 protocols (HTTP, HTTPS, TCP, UDP, KCP/ICMP). Windows and Linux variants observed. Uses RC4 encryption with hardcoded keys. Deployed in attacks against U.S. state government networks and global telecommunications providers.",
  },
  {
    id: "ioc-hash-008",
    slug: "hash-d5e6f7a8b9c0d1e2",
    type: "hash_sha256",
    value: "d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6",
    threat_type: "Espionage Implant",
    threat_actor: "APT28",
    malware_family: "X-Agent",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2024-01-20",
    last_seen: "2025-11-14",
    tags: ["apt28", "fancy-bear", "xagent", "sofacy", "gru", "espionage"],
    source: "SENTINEL APEX TI / ESET / Symantec",
    mitre_tactics: [
      { id: "T1056.001", name: "Keylogging", tactic: "Collection" },
      { id: "T1113", name: "Screen Capture", tactic: "Collection" },
    ],
    tlp: "GREEN",
    description:
      "X-Agent (Sofacy/Sednit) espionage implant used by APT28 / GRU Unit 26165. Modular architecture supports keylogging, file exfiltration, screen capture, and remote shell. This Windows variant communicates over custom SSL to avoid detection. Used in operations targeting NATO governments, election infrastructure, and defense contractors.",
  },
  {
    id: "ioc-hash-009",
    slug: "hash-e7f8a9b0c1d2e3f4",
    type: "hash_sha256",
    value: "e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8",
    threat_type: "Cryptocurrency Theft",
    threat_actor: "Lazarus Group",
    malware_family: "AppleJeus",
    confidence: "HIGH",
    severity: "CRITICAL",
    first_seen: "2024-03-08",
    last_seen: "2026-04-11",
    tags: ["lazarus", "dprk", "applejeus", "macos", "crypto-theft"],
    source: "SENTINEL APEX TI / CISA AA21-048A / KISA",
    mitre_tactics: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access" },
      { id: "T1553.002", name: "Code Signing", tactic: "Defense Evasion" },
    ],
    tlp: "GREEN",
    description:
      "AppleJeus macOS variant used by Lazarus Group (DPRK Bureau 121) to steal cryptocurrency from exchange employees. The DMG installer is signed with a legitimate Apple Developer certificate obtained fraudulently. Post-installation, the trojanized trading app contacts Lazarus C2 infrastructure to exfiltrate wallet credentials and private keys.",
  },
  {
    id: "ioc-hash-010",
    slug: "hash-f9a0b1c2d3e4f5a6",
    type: "hash_sha256",
    value: "f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0",
    threat_type: "Remote Access Trojan",
    threat_actor: null,
    malware_family: "AsyncRAT",
    confidence: "HIGH",
    severity: "HIGH",
    first_seen: "2025-06-03",
    last_seen: "2026-05-20",
    tags: ["asyncrat", "open-source-rat", "vbs-dropper", "info-stealer"],
    source: "SENTINEL APEX TI / ANY.RUN / Cofense",
    mitre_tactics: [
      { id: "T1219", name: "Remote Access Software", tactic: "Command and Control" },
      { id: "T1082", name: "System Information Discovery", tactic: "Discovery" },
    ],
    tlp: "GREEN",
    description:
      "AsyncRAT sample delivered via phishing emails containing malicious VBS scripts inside .zip attachments. AsyncRAT is an open-source C# remote access tool abused for keylogging, screen recording, file exfiltration, and cryptocurrency wallet theft. This campaign variant added AMSI bypass and process-level AV evasion techniques.",
  },
];

export function getIocBySlug(slug: string): IocRecord | undefined {
  return IOC_RECORDS.find((ioc) => ioc.slug === slug);
}
