#!/usr/bin/env python3
"""
detection_engine.py — CyberDudeBivash v11.5 (SENTINEL APEX ULTRA)
UPGRADED: Production-ready Sigma and YARA rule generation with real IOC data.
Generates meaningful detection rules even when IOC data is limited.
"""
import re
import yaml
from datetime import datetime, timezone
from typing import Dict, List


class DetectionEngine:
    """Enterprise-grade automated detection rule synthesis."""

    def generate_sigma_rule(self, title: str, iocs: Dict) -> str:
        """
        Generates a production-ready, SIEM-agnostic Sigma rule.
        Enhanced: Handles multiple IOC types, produces valid rules
        even with empty IOCs using behavioral patterns.
        """
        domains = iocs.get('domain', [])
        ips = iocs.get('ipv4', [])
        urls = iocs.get('url', [])
        hashes = iocs.get('sha256', []) + iocs.get('md5', [])
        artifacts = iocs.get('artifacts', [])
        cves = iocs.get('cve', [])

        safe_title = re.sub(r'[^a-zA-Z0-9 _-]', '', title)[:80]
        date_str = datetime.now(timezone.utc).strftime('%Y/%m/%d')

        rules = []

        # Rule 1: Network IOCs (domains + IPs)
        if domains or ips:
            net_indicators = (domains[:10] + ips[:10])
            rule = {
                'title': f'CDB-Sentinel: {safe_title} - Network IOCs',
                'id': f'cdb-{abs(hash(title)) % 999999:06d}',
                'status': 'experimental',
                'description': f'Detects network connections to infrastructure associated with: {safe_title}. Auto-generated by CyberDudeBivash Sentinel APEX.',
                'references': ['https://cyberdudebivash.com', 'https://cyberbivash.blogspot.com'],
                'author': 'CyberDudeBivash GOC (Automated)',
                'date': date_str,
                'tags': ['attack.command_and_control', 'attack.exfiltration'],
                'logsource': {'category': 'dns', 'product': 'any'},
                'detection': {
                    'selection_dns': {'query|contains': net_indicators[:8]},
                    'condition': 'selection_dns',
                },
                'falsepositives': ['Legitimate traffic to similarly named domains', 'Internal DNS resolution'],
                'level': 'high',
            }
            rules.append(yaml.dump(rule, default_flow_style=False, sort_keys=False))

        # Rule 2: File-based IOCs (hashes + artifacts)
        if hashes or artifacts:
            rule = {
                'title': f'CDB-Sentinel: {safe_title} - File Indicators',
                'id': f'cdb-{abs(hash(title + "file")) % 999999:06d}',
                'status': 'experimental',
                'description': f'Detects malicious file indicators associated with: {safe_title}.',
                'author': 'CyberDudeBivash GOC (Automated)',
                'date': date_str,
                'tags': ['attack.execution', 'attack.defense_evasion'],
                'logsource': {'category': 'file_event', 'product': 'windows'},
                'detection': {},
                'falsepositives': ['Legitimate software with matching names'],
                'level': 'high',
            }
            if hashes:
                rule['detection']['selection_hash'] = {'Hashes|contains': hashes[:5]}
            if artifacts:
                rule['detection']['selection_file'] = {'TargetFilename|endswith': artifacts[:5]}
            conditions = [k for k in rule['detection'].keys()]
            rule['detection']['condition'] = ' or '.join(conditions)
            rules.append(yaml.dump(rule, default_flow_style=False, sort_keys=False))

        # Rule 3: Behavioral detection (always generated as fallback)
        title_lower = title.lower()
        process_patterns = []
        if any(w in title_lower for w in ['powershell', 'script', 'clickfix']):
            process_patterns = ['powershell.exe', 'pwsh.exe', 'wscript.exe', 'cscript.exe']
        elif any(w in title_lower for w in ['malware', 'trojan', 'backdoor', 'stealer']):
            process_patterns = ['cmd.exe', 'powershell.exe', 'rundll32.exe', 'regsvr32.exe']
        elif any(w in title_lower for w in ['exploit', 'cve', 'vulnerability', 'rce']):
            process_patterns = ['cmd.exe', 'powershell.exe', 'certutil.exe', 'bitsadmin.exe']
        else:
            process_patterns = ['powershell.exe', 'cmd.exe', 'mshta.exe', 'wmic.exe']

        behavioral_rule = {
            'title': f'CDB-Sentinel: {safe_title} - Behavioral Detection',
            'id': f'cdb-{abs(hash(title + "behav")) % 999999:06d}',
            'status': 'experimental',
            'description': f'Behavioral detection for TTPs associated with: {safe_title}. Detects suspicious process execution patterns.',
            'author': 'CyberDudeBivash GOC (Automated)',
            'date': date_str,
            'tags': ['attack.execution', 'attack.persistence'],
            'logsource': {'category': 'process_creation', 'product': 'windows'},
            'detection': {
                'selection': {
                    'Image|endswith': process_patterns,
                    'CommandLine|contains': ['-enc', '-nop', '-w hidden', 'bypass',
                                             'downloadstring', 'invoke-', 'iex('],
                },
                'condition': 'selection',
            },
            'falsepositives': ['Legitimate administrative scripts', 'Software deployment tools'],
            'level': 'medium',
        }
        rules.append(yaml.dump(behavioral_rule, default_flow_style=False, sort_keys=False))

        return '\n---\n'.join(rules)

    def generate_yara_rule(self, title: str, iocs: Dict) -> str:
        """
        Generates a production-ready YARA rule for memory and disk forensics.
        Enhanced: Includes actual IOC strings and behavioral patterns.
        """
        ips = iocs.get('ipv4', [])
        domains = iocs.get('domain', [])
        hashes = iocs.get('sha256', []) + iocs.get('md5', [])
        artifacts = iocs.get('artifacts', [])
        urls = iocs.get('url', [])

        rule_name = re.sub(r'[^a-zA-Z0-9_]', '_', title)[:40]
        date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

        strings_section = []
        string_idx = 0

        # Add IP indicators
        for ip in ips[:5]:
            strings_section.append(f'        $ip{string_idx} = "{ip}" ascii wide')
            string_idx += 1

        # Add domain indicators
        for d in domains[:5]:
            strings_section.append(f'        $dom{string_idx} = "{d}" ascii wide nocase')
            string_idx += 1

        # Add artifact filenames
        for a in artifacts[:3]:
            strings_section.append(f'        $file{string_idx} = "{a}" ascii wide nocase')
            string_idx += 1

        # Add URL indicators
        for u in urls[:3]:
            # Truncate long URLs
            u_short = u[:100]
            strings_section.append(f'        $url{string_idx} = "{u_short}" ascii wide')
            string_idx += 1

        # Always add behavioral strings based on threat type
        title_lower = title.lower()
        if any(w in title_lower for w in ['powershell', 'script', 'clickfix']):
            strings_section.extend([
                f'        $beh{string_idx} = "powershell" ascii wide nocase',
                f'        $beh{string_idx+1} = "-EncodedCommand" ascii wide nocase',
                f'        $beh{string_idx+2} = "Invoke-Expression" ascii wide nocase',
                f'        $beh{string_idx+3} = "nslookup" ascii wide nocase',
            ])
            string_idx += 4
        elif any(w in title_lower for w in ['malware', 'trojan', 'stealer', 'rat']):
            strings_section.extend([
                f'        $beh{string_idx} = "CreateRemoteThread" ascii wide',
                f'        $beh{string_idx+1} = "VirtualAllocEx" ascii wide',
                f'        $beh{string_idx+2} = "WriteProcessMemory" ascii wide',
                f'        $beh{string_idx+3} = "NtUnmapViewOfSection" ascii wide',
            ])
            string_idx += 4
        elif any(w in title_lower for w in ['ransomware', 'ransom', 'encrypt']):
            strings_section.extend([
                f'        $beh{string_idx} = "vssadmin delete shadows" ascii wide nocase',
                f'        $beh{string_idx+1} = "bcdedit /set" ascii wide nocase',
                f'        $beh{string_idx+2} = ".onion" ascii wide',
                f'        $beh{string_idx+3} = "YOUR FILES HAVE BEEN" ascii wide nocase',
            ])
            string_idx += 4
        else:
            strings_section.extend([
                f'        $beh{string_idx} = "cmd.exe /c" ascii wide nocase',
                f'        $beh{string_idx+1} = "whoami" ascii wide',
                f'        $beh{string_idx+2} = "net user" ascii wide nocase',
            ])
            string_idx += 3

        if not strings_section:
            strings_section = [
                '        $gen0 = "cmd.exe" ascii wide',
                '        $gen1 = "powershell" ascii wide nocase',
            ]

        strings_block = '\n'.join(strings_section)

        # Determine condition based on what we have
        if string_idx > 6:
            condition = "3 of them"
        elif string_idx > 3:
            condition = "2 of them"
        else:
            condition = "any of them"

        yara = f"""rule CDB_{rule_name} {{
    meta:
        author = "CyberDudeBivash GOC"
        description = "Detects indicators associated with: {title[:60]}"
        date = "{date_str}"
        reference = "https://cyberbivash.blogspot.com"
        severity = "high"
        tlp = "TLP:CLEAR"

    strings:
{strings_block}

    condition:
        uint16(0) == 0x5A4D and filesize < 10MB and {condition}
}}"""

        return yara


detection_engine = DetectionEngine()
